opencontainers/runtime-spec

README.md
These actions need consistent tooling, and they're the sweet spot for
tools like runc.  Once you map the container spec to the filesystem,
the other actions (copy, snapshot, upload, download) can all be
handled by existing tools (e.g. POSIX's 'cp', 'btrfs subvolume
snapshot', netcat, etc.).  If existing tooling for those actions is
not sufficiently portable, new portable tools can be written, but that
should be separate from the container-specific stuff here.
I'm not sure about the intended meaning of the 'tagged' action.  Was
that intended for discoverability ("I want a container named 'Nginx'")
or auth ("Is my local /srv/nginx the same container 'Nginx' that Bob
audited?").  I think both are independent of the container runtime
though.
=> README: Focus on local runtime (create/start/stop)

config-linux.md
@philips @crosbymichael Rebased and updated.
=> Adds user namespace to the list of namespaces

config-linux.md
=> Makes namespaces description linux specific

config-linux.md
=> Adds section for Linux Sysctl.

config-linux.md
=> Adds link to kernel cgroups documentation

config-linux.md
=> Adds section for Linux Rlimits

config-linux.md
Signed-off-by: Zefan Li <lizefan@huawei.com>
=> Fix typos in the rlimits section

config.md
- Standardise on singular rather than plural
- Small formatting fixes
=> config.md: minor clean up of process specification

config-linux.md
=> Adds a section for user namespace mappings

spec.go
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>
=> typo: containers -> container's

config-linux.md, spec_linux.go
this is based on discussion on https://github.com/opencontainers/specs/issues/56
@mrunalp @philips
=> make rootfs mount propagation mode settable

README.md
=> spec: rename ocp to oci and add a link

config-linux.md
=> specs: add json notation

spec_linux.go
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>
=> typo: the -> for

README.md
This adds information for new participants to join the mailing list and
weekly meeting.
=> Update readme with weekly call and mailing list

README.md
To get everyone on the same page on what the bundle spec can do I want to enumerate reasonable use cases. I have two follow-up PRs that are discussion points for use cases that I don't think are reasonably covered.
=> bundle: add initial run use case

.travis.yml
https://github.com/opencontainers/specs/issues/90
Signed-off-by: Vincent Batts <vbatts@redhat.com>
=> .: adding travis file for future CI

README.md
On Sat, Aug 08, 2015 at 08:23:21AM -0400, Vincent Batts [wrote][1]:
> We said the topics would be proposed on this list. Discussion notes have
> been shared as a Google doc so far. I'm not opposed to markdown notes, but
> initially that just seems like an repo to me.
While touching this paragraph, I also re-wrapped it to match
README.md#markdown-style.
[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/41jZ9Qe7R5c/ZInajC_0DgAJ
=> README: Document pre-meeting agenda alteration

config-linux.md
Signed-off-by: ChengTiesheng <chengtiesheng@huawei.com>
=> Fix typos in the "Namespace types" section

runtime-config-linux.md
Details in the commit messages.
=> runtime-config-linux: Minor header cleanups after #88

runtime_config_linux.go
=> Fix LinuxRuntime field

runtime_config.go, runtime_config_linux.go
=> runtime_config: comments for golint

README.md, code-of-conduct.md
=> *: adding a code of conduct

README.md, bundle.md, config-linux.md, config.md, runtime-config-linux.md, runtime.md
Closes https://github.com/opencontainers/specs/issues/83
cc @philips @crosbymichael @mrunalp 
=> *.md: markdown formatting

.tools/validate.go
"commiter" is typo.
:%s/Commiter/Committer/g
:%s/commiter/committer/g
And do gofmt
=> Change commiter to committer

code-of-conduct.md
=> *: remove superfluous comma in code-of-conduct

.tools/validate.go
=> .tools: make GetFetchHeadCommit do what it says

runtime-config-linux.md
Signed-off-by: Gao feng <omarapazanadi@gmail.com>
=> move the description of Rlimits before example

runtime_config_linux.go
=> Change HugepageLimit.Limit type to uint64

version.go
Signed-off-by: linzhinan <linzhinan@huawei.com>
=> Change version from 0.1.0 to 0.2.0

runtime-config.md
=> runtime.md: fix spacing

README.md
Closes #127
This just takes the same changes in 127 but does not have 3 commits.  
Thanks @RobDolinMS for the content. 
=> Update readme with wiki link to minutes

config_linux.go, runtime_config_linux.go
=> Use unsigned for IDs

runtime-config.md
=> Remove trailing comma in hooks json example

version.go
=> Remove extra space from VersionMinor

README.md
Signed-off-by: Zefan Li <lizefan@huawei.com>
=> README: Fix some headers

runtime-config.md
=> lifecycle: no hyphens

ROADMAP.md
Signed-off-by: Liang Chenye <liangchenye@huawei.com>
=> add testing framework to ROADMAP

runtime_config_linux.go
Codes in specs should be decent, first of all should make
golint happy.
=> Fix golint warnings

README.md, ROADMAP.md
=> roadmap: update links and add wiki reference

bundle.md
Signed-off-by: GyuYong Jung <obliviscence+git@gmail.com>
=> Fix typo in Filesystem Bundle

ROADMAP.md
=> ROADMAP: adding distribution format line item

runtime.md
=> specs: fix typo

Makefile, specs-go/config_ffjson.go
Just from the ordering of the commits this was missed in the PR when it was merged.  
=> Regenerate ffjson for Timeout field

.travis.yml
https://github.com/opencontainers/runtime-spec/pull/366/files/af056a3e9e61c0dc4738f24c35816d2a02d86607#r59321215
=> travis: check commits for whitespace errors

Makefile, README.md
=> Add project.md to table of contents

.gitignore
=> Add schema/validate to .gitignore

README.md
=> [ReadMe] Consistent indented portions of Table of Contents

runtime.md
=> [ Runtime | State] Fix typo

config.md
=> config: clarify annotations sentence

Makefile
=> travis: have make target be travis sensitive

config.md
"must" --> "MUST" for RFC 2119 compliance
This replaces PR #403 which required a rebase
=> [Config] Capitalize MUST in config.md

.travis.yml
We've just done this on the image-spec. Works well.
=> travis: regress on failure to produce docs

schema/validate.go
=> schema/validate: Support reading documents via stdin

specs-go/config.go
Signed-off-by: Abhijeeth Nuthan <abhijeeth.nuthan@oracle.com>
=> Correction to User struct in specs-go/config.json

specs-go/config.go
Signed-off-by: John Howard <John.Howard@microsoft.com>
Minor typo specified --> specifies
=> Typo in apparmorprofile comment

README.md
=> Add a working call-in number

.pullapprove.yml
Closes #516
PullApprove has support to check for DCO
Also, take the time to improve the approve_regex
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add DCO check via PullApprove

implementations.md
Signed-off-by: James Hunt <james.o.hunt@intel.com>
=> Add "cc-oci-runtime" to implementations list.

schema/defs.json
=> add timeout for Hook

schema/config-linux.json, schema/defs-linux.json
=> add devices for resources and DeviceCgroup

schema/config-linux.json
=> remove unneeded item from seccomp

config.md
Found a minor typo in `config.md`
=> Fix typo 'unkown'

implementations.md
=> implementations: Rename ocitools -> runtime-tools

runtime.md
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
=> Add some related docs links

GOVERNANCE.md
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
=> Fix typo: ammended -> amended

config-solaris.md, config.md
Adding Solaris support for mounts and correcting manpage section since Solaris moved the manpages around. 
Signed-off-by: Abhijeeth Nuthan abhijeeth.nuthan@oracle.com
=> Mounts in Solaris

glossary.md
=> [Glossary] Add anchor tags for headings

config-solaris.md
=> [Config Solaris] Add anchor tags for headings

config-linux.md
Replaces #577
Signed-off-by: Rob Dolin (MSFT) <robdolin@microsoft.com>
=> [Config Linux] Clarify: App --> Container

schema/config-linux.json, schema/defs-linux.json
=> schema: fix invalid string reference

schema/config-linux.json, schema/config-schema.json, schema/defs-linux.json, schema/defs.json
=> schema: fix invalid types

config.md
=> add REQUIRED to platform field

config-linux.md
=> config-linux.md: fix info

schema/state-schema.json
https://github.com/opencontainers/runtime-spec/blame/master/runtime.md#L19
=> state-schema.json: add the value of status

config-linux.md, schema/defs-linux.json, specs-go/config.go
=> Add new architectures from libseccomp 2.3.2

specs-go/version.go
vote: https://groups.google.com/a/opencontainers.org/d/msg/dev/QaGv2f9nbOQ/yOuCicrTAwAJ
d87ec69 Merge pull request #687 from jlbutler/link-cleanup-676
f47e43c Merge pull request #705 from q384566678/test-seecomp
7da699d Merge pull request #532 from wking/tk/restore-hook-lifecycle
41839d7 Merge pull request #707 from mrunalp/anchor_tags
40474dd Merge pull request #704 from hqhq/use_uint64_for_memory
2db8391 Merge pull request #699 from crosbymichael/mount-optional
2d491b0 Merge pull request #694 from q384566678/state-json
fb76f47 Merge pull request #696 from q384566678/json-fix
18965b0 Merge pull request #697 from q384566678/config-linux-fix
472cdae Merge pull request #695 from q384566678/config-fix
ae7a541 Merge pull request #657 from GrantSeltzer/improve-seccomp-spec
3f5078d Merge pull …
=> Bump version

ChangeLog
I'd [mentioned this branch in the `dev@` thread][1], but it didn't make it into the tagged release.
[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/QaGv2f9nbOQ/5MxnWLzYAwAJ
=> ChangeLog: Document changes since v1.0.0-rc4

implementations.md
Just like #741, but for another anchor.
=> implementations: Fix 'name"..."' -> 'name="..."' runtime anchor

config-linux.md
=> Use MUST and MAY for weight and leafWeight

config-linux.md
=> config-linux.md: Update the link to the devices

schema/config-schema.json
=> schema: add username for user field

config-linux.md
=> config-linux.md: add link for mknod

config-windows.md, specs-go/config.go
=> config.go: tiny tfix

specs-go/config.go
Signed-off-by: Tibor Vass <teabee89@gmail.com>
=> Fix "omitempty" typo

schema/config-linux.json
Signed-off-by: 0x0916 <w@laoqinren.net>
=> schema/config-linux: s/throttleWriteIopsDevice/throttleWriteIOPSDevice/

schema/config-linux.json
=> config-linux: add intelRdt field

schema/config-solaris.json
=> config-solaris: Replaced refs with actual fields in cappedCPU, cappedMemory and anet fields

config-linux.md
=> Fix typo psuedo->pseudo

schema/config-linux.json
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
=> schema: add allowed values for defaultAction

implementations.md
Added the Kata Containers project runtime to the list of
implementations.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
=> docs: Added kata-runtime to implementations

specs-go/config.go
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
=> vm: fix parameters field

config-windows.md
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>
=> Update Windows LayerFolder docs

schema/config-linux.json, schema/config-schema.json, schema/defs-linux.json, schema/defs.json
Closes: https://github.com/opencontainers/runtime-spec/issues/1023
=> schema: add missing definition for personality

MAINTAINERS
=> MAINTAINERS: remove Vishnu

RELEASES.md
Fix typo in RELEASES.md
compatibity -> compatibility
formating -> formatting
Try PR again because signed-off failed.
Signed-off-by: Joowon Cheong <jwcheong0420@gmail.com>
=> Fix typo in RELEASES.md

config-linux.md
=> config-linux: add SHOULD to linux.namespaces.type

ChangeLog, Makefile, specs-go/version.go
Fixes #1010
VOTE: https://groups.google.com/a/opencontainers.org/d/msg/dev/8GeFsgXvSM8/lTwNIWlOBAAJ
=> Release v1.0.2

MAINTAINERS
=> MAINTAINERS: update vbatts email

config-linux.md
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
=> config-linux: fix personality link

spec.md
RFCs where moved to https://www.rfc-editor.org/rfc/
=> fix RFC link

GOVERNANCE.md, RELEASES.md
Like https://github.com/opencontainers/image-spec/commit/bc44f5ba7198c331d70723a538f0a529b660aa92
=> GOVERNANCE: correct the Charter URL

CODEOWNERS
Follow-up to:
- https://github.com/opencontainers/runtime-spec/pull/1150
=> CODEOWNERS: sync with MAINTAINERS

schema/config-linux.json
Commit b6980b01b03bd7ec89370c9ce9e3c52c0798d259 introduced the issue.
I also checked other files like so `diff -u config-linux.json <(jq --indent 4 . config-linux.json)`.
=> schema: remove duplicate keys

features-linux.md, features.md, glossary.md, spec.md
Because "document" sounds like a human-readable document
=> glossary: s/features document/Features structure/g

features.md
there is a wrong link to config.md. I correct the link
=> fix link to hooks in features

schema/config-schema.json, schema/defs-zos.json, schema/features-linux.json, schema/features-schema.json, schema/test/config/good/spec-example.json, schema/test/config/good/zos-minimal.json, schema/test/features/good/runc.json
run `make -C schema fmt`, cause diff.
=> chore: format JSON file
