- config.md
- Fix some typos
- Move the example of hostname above "Resource Constraints"
Signed-off-by: Zefan Li <lizefan@huawei.com>
> Fix typos in config.md

- config-linux.md
- config.md
This moves some of the linux specific options like namespaces and
devices to the linux config document.  It also removes processes as an
array and replaces it with a single process.
It adds the "platform" struct for OS and Arch and updates many of the
examples to match the changes.  I also remove some of the redundant
windows examples on the portable spec document because they did not add
any extra value and many values were the same.
> Move linux specific options to linux spec

- config.md
- standardise on "filesystem" instead of the previous mix of "file
system" and "filesystem"
- change "Machine-specific" to the more accurate "Platform-specific"
- move towards zeroth article for all field specifications
- grammar tweaks
> config.md: various cleanup/consistency fixes

- spec.go
- spec_linux.go
- version.go
This adds Go types implementing the configuration specification.
Closes #42
I also took the liberty to clean up the resource types because some of the names did not make sense at all and was pretty bad.  
> Add Go types for specification

- spec_linux.go
I'm not able to start runc on ubuntu 14.04 with kernel version 3.13, and it's because runc fails to set swappiness.
This patch adds memory.swappiness to the spec, and then I'll send out patches to support setting swappiness in runc so we'll be able to leave swappiness as the system default value.
> Add memory swappiness to linux spec

- bundle.md
- Move to single root filesystem, as the configuration specification now
only supports a single process
- Clarify that signatures are just another kind of content directory
- Cross-reference configuration specification for config.json
I think my understanding w.r.t. the rootfs stuff is correct, but I could be totally off-base on this; if so it's not at all clear to me what the purpose of multiple rootfs directories is.
> bundle.md: various updates to latest spec

- spec_linux.go
> Rename SystemProperties to Sysctl

- config-linux.md
- config.md
- link to official SemVer page
- link between config.md and config-linux.md and explain relationship
- fix typo (arch -> os)
- tweak formatting of some special characters
> config: minor cleanup

- LICENSE
- README.md
This adds the apache 2 license and DCO information for contributions to this repository. 
> Add license and DCO information for contributions

- config-linux.md
- spec_linux.go
'From' and 'To' are potentially ambiguous for a one-to-one map like
this, and there's already an established name convention in
SysProcIDMap [1].  This commit removes the mental overhead of two
separate naming schemes for the same information.  I'd like to drop
IDMapping entirely in favor of SysProcIDMap, but SysProcIDMap doesn't
give the JSON hints we need for (de)serializing.
[1]: https://golang.org/pkg/syscall/#SysProcIDMap
> spec_linux.go: Rename IDMapping fields to follow syscall.SysProcIDMap

- bundle.md
The three files/directory are at the same level in the bundle directory,
they should be aligned.
> specs: align the ascii graph

- runtime.md
"oc" is too short to understand here, "runc" seems better.
> runtime.md: convert oc to runc

- config-linux.md
The fields in the [ug]idMappings are changed, we should fix
the description correspondingly.
> specs: fix the description for the [ug]idMappings

- README.md
This is something we learned in the appc spec: collaborating on english prose in plain-text with git is hard, and you need rules to make it easier.
> README: add a rule for paragraph formatting in markdown

- runtime.md
- spec.go
See #20 
Starting with pre-start and post-stop and then will add more specific hooks tied to namespaces in Linux.
> hooks: start with pre-start and post-stop hooks.

- config-linux.md
- spec_linux.go
It appeared that we need more control over devices, for example different permissions and choosing path on caller side.
> Replace Linux.Device with more specific config

- config-linux.md
- spec_linux.go
This is WIP for adding security settings as discussed in the meeting.
The settings are based on security profiles in nsinit and Seccomp configuration in https://github.com/opencontainers/runc/pull/70
> Add security section 

- README.md
- implementations.md
Adding an implementations page.
> Implementations page

- README.md
Leaning on aspects of golang's contribution
(https://golang.org/doc/contribute.html)
Signed-off-by: Vincent Batts <vbatts@redhat.com>
> README.md: contribution about discussion

- spec_linux.go
Change Device field order in spec_linux.go, 'Path' should be top of the 'Type' field, according to the different of the config-linux.md, 'Path' field is the unique key.
Signed-off-by: LinZhinan(Zen Lin) <linzhinan@huawei.com>
> Change Device field order in spec_linux.go

- bundle.md
- config-linux.md
- config.go
- config.md
- config_linux.go
- runtime-config-linux.md
- runtime-config.md
- runtime_config.go
- runtime_config_linux.go
Based on our discussion in-person yesterday it seems necessary to
separate the concept of runtime configuration from application
configuration. There are a few motivators:
- To support runtime updates of things like cgroups, rlimits, etc we
should separate things that are inherently runtime specific from
things that are static to the application running in the container.
- To support the goal of being able to move a bundle between hosts we
should make it clear what parts of the spec are and are not portable
between hosts so that upon landing on a new host the non-portable
options may be rewritten or removed.
- In order to attach a cryptographic identity to a bundle we must not
include details in the bundle that are host specific.
This is a WIP to generate discussion.
> specs: introduce the concept of a runtime.json

- README.md
- runtime-config-linux.md
And adjust wrapping on touched lines to match the README's “Markdown
style” suggestions.
I also added a missing period after the namepaces(7) link.
> Remove trailing whitespace

- runtime-config.md
- runtime_config.go
Don't use strings when you can use dictionaries/objects. JSON objects are trivial to parse and manipulate, unlike strings. String parsing is the #1 cause of security bugs, so if it can be trivially avoided, then why not ;)
> JSON objects are easier to parse/manipulate

- README.md
In #opencontainers after today's meeting, here's the source for the
change from Google Hangouts to BlueJeans:
12:01 < wking> Is the BlueJeans approach going to be our standard
procedure?  If so, I can file a PR updating our weekly-meeting docs
(which still talk about YouTube and Google Hangouts)
12:03 < mrunalp> wking: Yeah, I think so.
12:04 < wking> ok.  And it's just going to "push the BlueJeans link to
IRC and the list before the meeting"?  Or does BlueJeans have stable
channel URLs or similar?
12:05 < mrunalp> wking: The URL that we used today is stable.
And here's the source for archiving the minutes:
12:10 < wking> Will we still be posting mintes to the mailing-list, or
are they now just on the wiki
(https://github.com/opencontainers/specs/wiki)?
12:12 < mrunalp> wking: I am fine …
> README: Document BlueJeans for meetings

- runtime_config_linux.go
Fix a copy-paste error from 7232e4b1 (specs: introduce the concept of
a runtime.json, #88).
> runtime_config_linux: Fix 'LinuxSpec' -> 'LinuxRuntimeSpec' in comment

- runtime-config-linux.md
- runtime-config.md
These snuck in with 7232e4b1 (specs: introduce the concept of a
runtime.json, 2015-07-30, #88) and 73bf1ba8 (JSON objects are easier
to parse/manipulate, 2015-08-27, #120).
> runtime-config: Remove blank lines from the end of files

- config.md
The field is optional, but it's nice to have at least one example of
it in use.
Signed-off-by: W. Trevor King <wking@tremily.us>
> config: Add example cwd

- config.md
The field is optional, but it's nice to have at least one example of
it in use.  The GIDs I've chosen are currently "tty" and "disk" on
Gentoo (1 is "bin"), which may be remotely reasonable choices, but the
values we're using don't really matter without an example filesystem
to provide context.
Signed-off-by: W. Trevor King <wking@tremily.us>
> config: Add example additionalGids

- config_linux.go
- runtime_config_linux.go
It was lost in pull request about runtime config
> Return golint-compliant naming for mappings

- config.go
- config.md
- runtime-config.md
- runtime_config.go
Added info about MountPoints to config.md.
Filled after discuss in opencontainers/runc#242
I noticed that `MountPoints` still has json tag `mounts`, should I rename it to `mountPoints`?
> Change layout of mountpoints and mounts

- config.go
- runtime.md
- runtime_config_linux.go
This adds runtime state information for oci container's so that it can
be persisted and used by external tools.
Closes #72
Closes #41 
> Add runtime state configuration and structs

- config.md
Looks like these didn't get updated when `spec.go` and `spec_linux.go` were renamed.
> Fix links to go files in config.md

- runtime.md
- runtime_config_linux.go
In an effort to be more discoverable and self-describing change out the
term "oci" for "opencontainer". We should consider using this as the
prefix for global namespaces going forward as oc has conflicts with
existing tools and oci is the name of the initiative not the specs.
> runtime: use opencontainer vs oci

- runtime-config-linux.md
- runtime_config_linux.go
Add support for the PIDs cgroup as a cgroup resource constraint in the
Linux container specification. Since PIDs are a real resource, we need
to support the ability to limit them.
The PIDs cgroup subsystem is available in Linux 4.3+.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
I realised while implementing opencontainers/runc#58 that if we want to
have PIDs support in the `config.json` we need to update the spec too.
> spec: linux: add support for the PIDs cgroup

- runtime_config_linux.go
Since the spec and the reference implementation are [currently out of sync on the names of the namespaces](https://github.com/opencontainers/runc/pull/247) (and the [spec and its own examples are out of sync too](https://github.com/opencontainers/specs/pull/149)) it seems wise to define these constants somewhere.
Note that this assumes the constants currently used by RunC are adopted for consistency (rather than vice versa) as discussed in https://github.com/opencontainers/runc/pull/247 and proposed in https://github.com/opencontainers/specs/pull/152. Happy to change the constants defined here to whichever of runc or the spec we decide is right, but I wanted to open the PR so we could discuss the concept.
> Define constants for Linux Namespace names

- runtime-config-linux.md
"mount" rather than "mnt", "network" rather than "net"
If we prefer the longer form names. This would supersede #149 and https://github.com/opencontainers/runc/pull/247
> Make namespace names match runc

- config-linux.md
Fixes #95
Signed-off-by: Brandon Philips <brandon.philips@coreos.com>
> config-linux: specify the default devices/filesystems available

- runtime-config-linux.md
- runtime_config_linux.go
> Change the rlimit type to string instead of int

- config-linux.md
- config_linux.go
- runtime-config-linux.md
There are two RootfsPropagation fields, one is Linux.RootfsPropagation,
the other one is LinuxRuntime.RootfsPropagation. They are duplicated,
one of them should be removed.
The RootfsPropagation is definitely a runtime specific configuration,
so we remove the one of Linux.RootfsPropagation.
And the description of it is moved from config-linux.md to
runtime-config-linux.md.
> Deduplicate the field of RootfsPropagation

- runtime-config.md
c18c283 (Change layout of mountpoints and mounts, 2015-09-02, #136)
removed the destination field from the Go type and examples, but
[forgot to remove it from the documentation][1].  Fix that with this
commit.
[1]: https://github.com/opencontainers/specs/issues/109#issuecomment-138531616
> runtime-config: Remove 'destination' docs from mounts

- config-linux.md
> Modify the capabilities constants to match header files like other constants

- .tools/validate.go
merged PRs do not have DCO, so do not check for them
https://github.com/opencontainers/specs/issues/169
> travis: fix DCO validation for merges

- runtime-config-linux.md
- runtime_config_linux.go
Related to #114
This change should be useful for exec'ing new processes in an existing container.
> Adding cgroups path to the Spec.

- runtime-config-linux.md
> Clarify behavior around namespaces paths

- README.md
- version.go
For deterministic comparison and still providing a Version string for
representation and reuse.
> version: more explicit version for comparison

- README.md
pulled from http://chris.beams.io/posts/git-commit/
> README.md: adding a git style guide

- config_linux.go
config_linux.go already has the "_linux" for the go build,
so the build tag in the file is redundant.
> Remove the unneeded build tag from the config_linux.go

- runtime_config_linux.go
it's `blkio` in kernel doc and under /sys/fs/cgroup
> Fix typo in BlockIO struct comment

- runtime-config-linux.md
> runtime: config: linux: Remove trailing comma in namespaces json example

- runtime-config-linux.md
- runtime_config_linux.go
`WeightDevice`, `ThrottleReadBpsDevice`, `ThrottleWriteBpsDevice`, `ThrottleReadIOpsDevice`, `ThrottleWriteIOpsDevice` are now slices to well defined structs to allow setting multiple devices in their respective blkio file. By using a string to represents those values it wasn't possible to set correct values when multiple devices were passed in the config (either newline separated or comma separated).
I don't know how this worked before to define multiple devices for these cgroups resources. Writing something like `8:0 500\n8:16 300` isn't working (there's a Docker PR https://github.com/docker/docker/pull/13959 which passes that format to libcontainer and by passing that format to current master runc isn't working as well (neither using comma) because it just writes it to cgroup file …
> runtime: config: linux: Edit BlockIO struct

- runtime-config-linux.md
- runtime_config_linux.go
By default, Seccomp filters will only permit syscalls to be made using the
native architecture of the kernel. This is fine for most use cases, but breaks
others (such as running 32-bit code in a container on a host with a 64-bit
kernel). This PR adds a field to specify additional architectures which may
make syscalls in a container secured by Seccomp.
As with other the other aspects of Seccomp, Libseccomp's seccomp.h is used to provide string constants which can be used to represent these additional architectures.
> Add Architecture field to Seccomp configuration in Linux runtime

- README.md
- bundle.md
- code-of-conduct.md
- config-linux.md
- config.md
- principles.md
- runtime-config-linux.md
- runtime-config.md
- runtime-linux.md
- runtime.md
I'm sure this will cause a lot to need rebasing, but the layout was killing me.
I'm ready to move the source into a `./ref/go/` directory and start framing up protobuf structs or json-schema for a more canonical use as well, but that can wait for another change.
cc @mrunalp @philips @crosbymichael @LK4D4 @tianon @vishh
> Docs overhaul

- config.md
- runtime-config-linux.md
- runtime-config.md
- runtime.md
convert ```**name**``` to ```**`name`**```
we have both styles in the `*.md`, we should use only one of the styles.
And **`name`** is much prettier than **name** in the result,
so we use **`name`**
> convert **name** to **`name`**

- .travis.yml
> .travis.yml: add go 1.5.1, update from 1.4.2 to 1.4.3

- config.go
- runtime.md
> Rename State's Root to Bundle

- runtime-config.md
- runtime_config.go
> Add post-start hooks

- config.md
If we don't specify this, some bundle-authors or runtime-implementers
might expect the runtime to intelligently order mounts to get the
"right" order.  But that's not possible because:
$ mkdir -p a/b/c d/e/f h
$ tree --charset=ascii h
h
`-- c
But in the other order:
$ tree --charset=ascii h
h
`-- e
`-- f
So there's no "right" order.  Allowing the bundle-author to specify
their intended order is both easy to implement and unambiguous.
Spun off from #136.
> config: Require the runtime to mount Spec.Mounts in order

- runtime.md
> Add some clarity around the state.json file

- principles.md
I didn't really change much, just moved somes stuff around and expanded
a little more in number 5.
I moved all of the physical shipping container stuff to just the into
because while its a cute analogy, repeating it over and over just got
in the way of the real points - and by number 5 we ended up having more text
about shipping containers than our containers - which was just weird.
> Cleanup principles

- bundle.md
Mainly just moved stuff around, but also tried to add some clarity around
what is required w.r.t. naming and location of files/dirs.
But to highlight some things that I want to make sure we ALL agree on:
- config.json and runtime.json MUST use those exact names
- name of rootfs dir is user defined - but nudge them towards `rootfs`
- all 3 (config.json, runtime.json and rootfs dir) MUST all be in the same location/dir
- that 'location' is NOT part of the bundle itself (this may matter when someone defines the on-the-wire format of a bundle)
> Cleanup bundle.md

- implementations.md
Details in the commit messages, but basically, if we've heard of an
OCI-related tool, I think we should be linking it from here ;).
@kunalkushwaha and @mrunalp, I've done my best at one-line summaries
based on your READMEs, but I'm happy to reroll these commits if you
prefer different phrasing (just tell me what to put in ;).
> implementations: Add links to kunalkushwaha/octool and mrunalp/ocitools

- MAINTAINERS
Removing Victor Marmol and Rohit Jnagal from being Maintainers.
Signed-off-by: Vishnu kannan <vishnuk@google.com>
cc @crosbymichael @vmarmol @rjnagal
> Adding Vishnu Kannan as a Maintainer.

- runtime-config-linux.md
- runtime_config_linux.go
> Add oom_score_adj to the runtime Spec.

- runtime-config-linux.md
- runtime_config_linux.go
- add information to cgroup resources controllers with examples
- add pids cgroup information and example
- reflect kernel types
I'm submitting this as a first iteration of specifying structures here in the specs so any help/ideas are well accepted for subsequent PRs
> runtime: config: linux: add cgroups informations

- runtime_config_linux.go
Fix a misleading comment for how PidsLimit works when given a limit of
0. A limit of 0 is identical to a limit of 1, and so there is no reason
to distinguish the two. Since the default value for integers in Go is 0,
it makes more sense to make the default value mean that there is no
limit.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com> (github: cyphar)
> config: linux: update description of PidsLimit

- bundle.md
- config.go
- runtime_config.go
- state.go
Cover my action item from this week's OCI call.
Also moved State json out of config.go since its not really part of
the config.json file/config.
> Talk about host specific/independent instead of mutability

- ROADMAP.md
This adds the initial roadmap for the project.  I compiled this list from various weekly meetings, issues, and discussions on irc.  
This is not meant to be an absolute list of things that we will or will not do, just a way for our project to convey what we want to focus on and work towards.  I tried to add "owners" based on people who expressed interest in the various topics.  
Let me know what you all think.  We can use this overall list and break out topics for various milestones.   
> Add initial roadmap

- runtime-config-linux.md
> runtime-config-linux.md: fix the type of cpus and mems

- config.md
The UTS namespace is for [hostnames and NIS domain names][1].  Without
a new namespace, the hostname entry would clobber the host
environment's hostname.
Clobbering the host's hostname or a joined-namespace's hostname might
be acceptable for folks who trust their bundles, but it's not allowed
by the “error out if the config specifies anything else related to
that namespace” language that landed in 02b456e9 (Clarify behavior
around namespaces paths, 2015-09-08, #158).
[1]: http://man7.org/linux/man-pages/man7/namespaces.7.html
> config: Require a new UTS namespace for config.json's hostname

- bundle.md
We have `host-specific` and `host specific` in the same doc,
add hyphen to keep consistency.
> Add hyphen for host specific

- runtime.md
The version field was added while 180df9d (Add runtime state
configuration and structs, 2015-07-29, #87) was [in-flight][1], and it
missed getting documented in the example.
[1]: https://github.com/opencontainers/specs/pull/87#issuecomment-135117343
> runtime: Add 'version' to the state.json example

- README.md
It may not be flag day yet... but here's the PR to address issue #256
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
> adds text describing the upper-case keywords used in the spec

- runtime-config-linux.md
The former definition was join "/" when `cgroupsPath` is absent, it's
not clear whether to join the root cgroup or create a sub cgroup under "/".
Join root cgroup would be a bad idea cause that's not what a container
should do. And craete a sub cgroup would be missing definition about what
the cgroup name should that be.
So I think we should leave this to implementations what the default
cgroup path should be.
> Change the behavior when cgroupsPath is absent

- runtime.md
The lifecycle described is generic and should apply to all platforms.
It provides leeway for the runtimes to be flexible in how they
implement it.
Thanks to @crosbymichael for the feedback!
> Add lifecycle for containers

- runtime-config.md
I'm not sure if this is the intention here, but I think it'll be better
to keep consistency with golang packages.
> Clarify the meaning of hook elements

- runtime-config-linux.md
- runtime_config_linux.go
Signed-off-by: Dongsheng Yang <yangds.fnst@cn.fujitsu.com>
> cgroup: Add support for memory.kmem.tcp.limit_in_bytes

- runtime.md
As [discussed][0] in #231.  We [already require it for
Linux/Unix-based systems][1], so we don't have to repeat it here.  And
other systems will use different paths, which we haven't specified
yet.  When [I asked why we didn't specify a path for Windows][2],
[Vincent said we were waiting on help from PoC implementations][3].
So this commit punts the location to the “State” section, and lets the
“Lifecycle” section just focus on when the write-to-filesystem
happens.
There's also [discussion about removing the filesystem state registry
completely][4], in which case we'd want to remove the whole line from
the lifecycle.  If we expect to switch to something like [`--state
PATH`][5] in the near future this PR is just polishing dead
documentation.
[0]: …
> lifecycle: Don't require /run/opencontainer/<runtime>/containers

- runtime.md
As [discussed][1] [in][2] #231.  I'm in favor of [rolling it back into
`config.json`][3], but we [aren't there yet][4].  I also added
backticks around the filenames for consistency with bundle.md.
This seemed uncontroversial enough to go straight to a PR (and not via
a mailing list thread), but I'm happy to spin up a mailing list thread
around it if anyone thinks I'm overlooking a contentious issue.
[1]: https://github.com/opencontainers/specs/pull/231#discussion_r43262848
[2]: https://github.com/opencontainers/specs/pull/231/files#r46735828
[3]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/0QbyJDM9fWY
[4]: https://github.com/opencontainers/specs/blob/4a63e81a807edec3d67ed2b6bd99a6c2b288676f/bundle.md#container-format
> lifecycle: Mention runtime.json

- runtime_config_linux.go
Follow up of [this comment](https://github.com/opencontainers/specs/pull/199/files#r43151805)
> Fix cgroups value types in the spec.

- runtime_config_linux.go
/cc @vishh
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> runtime_config_linux.go: add missing pointer

- Makefile
I do not like having this build step of printable documentation
depending on pulling a container, but the pandoc+latex combo is a big
bundle. This is the minimal and cleanest approach for using these tools,
for now.
Just run `make pdf && xdg-open ./output/docs.pdf`
Per: https://github.com/opencontainers/specs/blob/master/ROADMAP.md#printablecompiled-spec
> *: printable documents

- project.md
Fairly simple. Docs for various project processes, starting with release process.
> Project: document release process

- README.md
- glossary.md
And link them to the more detailed specification.
This borrows from appc, which calls the launched process tree ["the
app"][1].  I don't see a point to abbreviating it, so I've gone with
"application".
Subsection titles for the entries will be obnoxiously spacious, but
the other alternatives seem worse:
* An HTML definition list (`<dl>`) would have nice default styling, but
it's annoying to write raw HTML.  And we would have needed
something like:
<dt name="bundle">Bundle</dt>
<dd>
A [directory structure](bundle.md) that is...
</dd>
to get Markdown-style links in the defintion itself.
* A Markdown list (`* …`) would have reasonable default styling, but
there's no Markdown syntax for adding anchors to the entries.  And a
glossary is much less useful if you can't link to a specific entry. …
> glossary: Provide a quick overview of important terms

- runtime-config-linux.md
It's officially pointer of uint64 now, no point it can be
-1, change it to 0 as other fields in example.
> Fix value of swappiness

- config.go
- config_linux.go
- runtime_config.go
- runtime_config_linux.go
per https://github.com/opencontainers/specs/pull/282#issuecomment-167134101
> Appropriately mark optional fields as omitempty

- MAINTAINERS
https://github.com/opencontainers/specs/pull/223#discussion-diff-48630276
Reported-by: W. Trevor King <wking@tremily.us>
> MAINTAINERS: correct Vish's github account

- Makefile
At the end of the list, to match its position in the README.  This
catches #107 up with #263, which I'd missed during one of the #107
rebases.
Signed-off-by: W. Trevor King <wking@tremily.us>
> Makefile: Add glossary to DOC_FILES

- config-linux.md
- runtime-config-linux.md
They should stay in runtime not config.
Signed-off-by: Gao feng <omarapazanadi@gmail.com>
> move the description of user ns mapping and default files to proper file

- runtime-config-linux.md
This is carrying #236, but deferring the description to the linux docs.
> runtime-config-linux: Add info to clarify oom_score_adj (carrying #236)

- Makefile
- README.md
- style.md
So we have something to cite to avoid rehashing established decisions.
Provide some motivation and links to the backing discussion so folks
can re-open these if they have new information that wasn't covered in
the original decision.
Like the glossary (18734986, glossary: Provide a quick overview of
important terms, 2015-08-11, #107), I've used subsection titles for
each entry to get link anchors.
I'm fine dropping any of the decisions from this PR if they turn out
to be contentious, and will happily add any that I missed if folks
bring them to my attention here.
Mailing-list suggestion [here][1], and I'm interpreting the absence of
feedback there, plus a maintainer proposing the same thing in #273 as
enough of a consensus to transition this idea into a PR.  If there is
pushback on the …
> style: Collect established conventions in a discoverable location

- ChangeLog
- version.go
done in such a way to have a taggable v0.2.0 and then bump to a v0.3.0-dev
This way it's still jive with semver 2.0 section 10
> Bumpversion v0.3.0

- runtime-config-linux.md
- runtime_config_linux.go
The just-landed style conventions (#287) prefer integers to hex
strings, and [I said I'd post an update for this setting if/when those
landed][2].  The kernel [uses uint32s for this setting][3].
[2]: https://github.com/opencontainers/specs/pull/287#discussion_r48899312
[3]: https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/include/net/cls_cgroup.h?id=refs/tags/v4.3#n24
> runtime-config-linux: Convert classID from hex to uint32

- ROADMAP.md
As using protobuf has been decided against, this removes it from the
Roadmap items.
> ROADMAP: remove the protobuf line item

- ROADMAP.md
We discussed this in the face to face meeting and agreed
that it makes sense to keep the rootfs as is for flexibility.
> Remove clarify rootfs item from the ROADMAP

- config.md
carrying forward #286 by making the field required
> Clarify cwd

- config.md
I think we agreed on this, but there is no docs for this, and it is easy to cause confusing as https://github.com/opencontainers/runc/pull/406 and https://github.com/opencontainers/runc/pull/406#issuecomment-157685174
> Clarify backwards compatibility for major version 0

- config.go
> config: corresponding change for required field

- style.md
pandoc/LaTeX is not happy with this shady character.
```
! Package inputenc Error: Unicode char \u8:↔ not set up for use with
LaTeX.
```
> style: remove unicode character

- config.md
> Make cwd an abs path to avoid ambiguity

- config.go
- config.md
https://github.com/opencontainers/specs/issues/110
> config: qualify the name of the version field

- README.md
I am trying to document who might want to read this spec. I constantly get asked who should be looking at OCI and why. Lets see how successful I am.
> README: add some user stories

- Makefile
For now, just vet and lint. But would like to include the commit
validator, once a good range is selectable.
> Makefile: add a target to run tests

- runtime-config-linux.md
- runtime_config_linux.go
This is a security setting that could be used to prevent processes in the
container from gaining additional privileges.
> Add NoNewPrivileges setting for linux

- runtime_config_linux.go
Converting to pointers to be consistent with other cgroups settings.
> Remove pointers for slices preferring omitempty tag instead 

- config-linux.md
- config_linux.go
This is #99 rebased onto the current master, because [the idea seems
to have new life][0].  It leaves mknod entries in **`linux.devices`**
and moves cgroups entries into **`linux.resources.devices`**.  Quiet
thread on the issue [here][1].
This makes it easy to distinguish between configs that call for cgroup
adjustments (which have linux.resources entries) from those that
don't.  Without this split, folks interested in making that
distinction would have to parse the device section to determine if it
included cgroup changes.  This will also make it easy to drop either
portion ([mknod][2] or [cgroups][3]) independently of the other if the
project decides to do so.
Using seperate sections for mknod and cgroups also allows us to avoid
the complicated validation rules needed for the combined …
> runtime-config-linux: Separate mknod from cgroups

- config-linux.md
With [34a9304a][1] (Merge branch 'for-4.5' of
git://git.kernel.org/pub/scm/linux/kernel/git/tj/cgroup, 2016-01-13),
Linux restructured their cgroups documentation.  This updated all of
our Documentation/cgroups references to match the new layout, using
[reference-style links][2] which let us collect link label definitions
at the bottom of the file.  That makes the spec source easier to read
(no distracting URLs in the middle of a sentence) and makes the URLs
easier to update (only one place to check / fix).
This builds on #298, so that PR should land first.
[1]: https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=34a9304a96d6351c2d35dcdc9293258378fc0bd8
[2]: http://daringfireball.net/projects/markdown/syntax#link
> config-linux: Update links to cgroups documentation

- style.md
The general rule seems to be:
> If Go's default value has the same semantics we'd use for an unset
> value, don't bother with a pointer.
I'm not sure how well that squares with [the pointer motivation][1],
which sounded like:
> We want a consistent way to identify unset settings.
But if the falsy values count as “unset”, maybe the “null is a
consistent identifier for unset” approach was never really viable.
I'm also not sure if the new style extends to integers where zero has
the same semantics as unset values.  It sounds like Michael [was ok
with no pointers for those values][2], but `OOMScoreAdj` (where zero
clearly means “do nothing”) [got a pointer in #233][3].  More clarity
on the threshold would be nice.
[1]: https://github.com/opencontainers/specs/pull/233#discussion_r47829711
[2]: …
> style: Document recent Go-pointer exceptions

- runtime.md
There are a few "OPEN" question in the doc that I'd like to brainstorm on.
> Expand on the definition of our ops

- README.md
BlueJeans requires a moderator while UberConference does not
> ReadMe: Replace BlueJeans with UberConference

- config-linux.md
- config_linux.go
Fixes: https://github.com/opencontainers/runc/issues/566
For type rune, we can assign char as 'c' in struct, but after
marshal, it'll be presented as int32. So it should be a
number in our example of json file. Otherwise we'll got error:
`json: cannot unmarshal string into Go value of type int32`
If we trying to unmarshal the json file.
> Fix type of devices type

- config-linux.md
- config.go
- config.md
- config_linux.go
This moves process specific settings like caps, apparmor, and selinux
process label onto the process structure to allow the same settings to
be changed at exec time.
> Move process specific settings to process

- config.md
These slipped through in 5a8a779f (Move process specific settings to
process, 2016-03-02, #329).
> config: Fix indents for process.apparmorProfile and .selinuxLabel

- config_linux.go
> Seccomp should be optional

- config_linux.go
- state.go
> Remove the state directory as we now have a state operation instead

- config.go
- config.md
> Add annotations and labels to the Spec.

- README.md
The only reference was removed in 15a43acd (ReadMe: Replace BlueJeans
with UberConference, 2016-02-24, #326).
> README: Drop BlueJeans link label definition

- specs-go/config.go
The label changed in 5a8a779f (Move process specific settings to
process, 2016-03-02, #329) and 7bf06d53 (source and schema:
differentiate with examples, 2015-12-18, #276) missed this instance
when rebasing around #329.
> specs-go/config: Fix 'SelinuxProcessLabel' -> 'SelinuxLabel'

- README.md
Update the Table of Contents section of the ReadMe.md to match the order
of the merged MarkDown files in the printable HTML and PDF outputs
> ReadMe: Update content to match print order

- schema/Makefile
- schema/defs-linux.json
- schema/defs.json
- schema/schema-linux.json
- schema/schema.json
- schema/validate.go
Conforming to https://tools.ietf.org/html/draft-zyp-json-schema-03
and http://json-schema.org/latest/json-schema-core.html
This work would ideally pair with separating the current reference source effort #276 
The gist of the `config.json` being tested with (may change periodically): https://gist.github.com/vbatts/5ac2723c9598875ffb0e
> json-schema: initial pass at schema and validator

- config-linux.md
- config.md
- specs-go/config.go
As discussed at the 9/3/16 weekly call and on IRC, this moves the rlimits struct on to process to match capabilities, apparmor, selinux etc which were moved in 5a8a779.
Also fixed a typo (`systemd` -> `systems`)
> Move rlimits to process

- config.md
- specs-go/config.go
1. Add 'omitempty' to 'Device'.
2. remove the 'seccomp' and 'device' from the example since they are not necessary
3. change the device type description `c` to "c" since it became a string.
Signed-off-by: liangchenye <liangchenye@huawei.com>
> add omitempty to 'Devices

- config.md
- project.md
It's pretty clear that the Go bindings cannot be canonical on their
own, because they do not define limits (e.g. the 0 through 512 range
for `FileMode`).  The JSON Schema is closer, but still does not cover
everything (e.g. “a directory must exist at **`root.path`**”).  Both
the Go bindings and the JSON Schema could grow to cover the full spec
by adding that sort of thing to comments and descriptions, but that's
not how things seem to be working now.
Also:
* Update links to Go bindings after 7bf06d5 (source and schema:
differentiate with examples, 2015-12-18, #276).
* Add a reference to the JSON Schema after cdcabde (schema: JSON
Schema and validator for `config.json`, 2016-01-19, #313).
> config: Make Markdown canonical

- config-linux.md
- glossary.md
Avoid trouble with situations like:
which uses the [required][1] [private][2] [mount][3] for binding mount
namespace references.  We want to avoid:
1. Runtime opens /mnt/test/mnt as fd 3.
2. Runtime joins the mount namespace referenced by fd 3.
3. Runtime fails to open /mnt/test/user, because /mnt/test is not
visible in the current mount namespace.
and instead get runtime authors to setup flows like:
1. Runtime opens /mnt/test/mnt as fd 3.
2. Runtime opens /mnt/test/user as fd 4.
3. Runtime joins the mount namespace referenced by fd 3.
4. Runtime joins the user namespace referenced by fd 4.
This also applies to new namespace creation.  We want to avoid:
1. Runtime clones a container process with a new mount namespace.
2. Container process fails to open /mnt/test/user, because /mnt/test
is …
> config-linux: Specify host mount namespace for namespace paths

- implementations.md
Now we have ocitools in opencontainers, thanks @mrunalp .
> Update associated projects

- config.md
- specs-go/config.go
So that runtimes don't lock up forever waiting on a hook to return I
added a timeout field.  This allows the author to specify the timeout in
seconds that they want the hook to run before aborting the hook and
container execution.
I think the hook is the proper place to specify a timeouot like this
because any type of overall timeout in the runtime will probably not
work for all hooks and will not be flexable enough.
Let me know that you all think.  
> Add timeout field to hooks

- ChangeLog
- config-linux.md
- project.md
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> *: fix typos

- config.md
> config: clarify the uname mapping

- .travis.yml
- Makefile
> travis: add go1.6 and work around golint

- style.md
> style: dangling paren

- README.md
We have these irclog2html.py logs [because we're part of a MeetBot
pool managed by the Linux Foundation][1], so they should be pretty
reliable.
We could have this link in the `/topic`, but there's already a lot
there and folks may want to browse the logs over HTTP without
bothering to connect to the live channel.
[1]: http://ircbot.wl.linuxfoundation.org/eavesdrop/%23opencontainers/%23opencontainers.2015-12-29.log.html#t2015-12-29T21:51:30
> README: Add a link to the IRC logs

- config-linux.md
- schema/schema-linux.json
- specs-go/config.go
Fixes #320
This adds the maskedPaths and readonlyPaths fields to the spec so that
proper masking and setting of files in /proc can be configured.
> Add masked and readonly paths

- README.md
- ROADMAP.md
- project.md
- style.md
> *: specs -> runtime-spec

- README.md
- style.md
This is style information, even though it's about the spec and not
about the behavior covered by the spec.  The Go-pointer rule is also
about more peripheral stuff though, and the README has a lot of stuff
in it, so it seems like a better fit after the move.
> style: Move one-sentence-per-line rule over from the README

- .travis.yml
They got rid of the repo. See https://groups.google.com/forum/#!searchin/golang-announce/vet|sort:relevance/golang-announce/qu_rAphYdxY/SR5jL9IDBgAJ
Thanks to @liangchenye for reporting.
> Fix the build by getting rid of go get for vet

- README.md
Proposed additional conformance language to support future certification work (cribbed from https://tools.ietf.org/html/rfc2616).
Closes #373 
Signed-off-by: Stephen R. Walli <stephen.walli@gmail.com>
> Additional language for conformance statement

- config-linux.md
Avoid the dangling “using” from e9a6d948 (cgroup: Add support for
`memory.kmem.tcp.limit_in_bytes`, 2015-10-26, #235).  I've tried to
echo the [kernel docs][1] by mentioning buffer memory.  I'd personally
prefer linking to the kernel docs and mentioning
`memory.kmem.tcp.limit_in_bytes`, but that seemed like too big of a
break from the existing style for this commit.
[1]: https://kernel.org/doc/Documentation/cgroup-v1/memory.txt
> config-linux.md: Reword kernelTCP docs and mention bytes

- config-linux.md
- config.md
- schema/defs-linux.json
- schema/schema-linux.json
- schema/schema.json
> Json schema and examples

- README.md
With:
$ sed -i 's/[[:space:]]*$//' README.md
fixing some trailing whitespace that snuck in with ca0803d1
(Additional language for conformance statement, 2016-04-06, #374).
Future occurrences should be caught by git-validation, which checks
for [whitespace][1] [issues][2] now.
[1]: https://github.com/vbatts/git-validation/pull/7
[2]: https://github.com/vbatts/git-validation/pull/9
> README: Remove trailing whitespace

- README.md
Weekly call is for all OCI projects and per discussion on today's call,
updates to indicate the call is for all OCI projects (rather than having
multiple calls.)
And updates time zone description from PST/PDT to Pacific time
This is carried PR from #368
Signed-off-by: Rob Dolin RobDolin@microsoft.com
> README: clarify weekly call

- config.md
- runtime.md
- style.md
This cleans up the anchoring of examples and adds to the style and conventions of such.
> Anchor examples

- .travis.yml
> travis: git-validation detects travis now

- schema/README.md
- schema/validate.go
> schema: add a README

- schema/Makefile
- schema/README.md
We should only download dependence without installing,
otherwise we'll probably get error:
go install: no install location for directory /home/qhuang/specs/schema outside GOPATH
For more details see: go help gopath
> Fix example in schema README

- runtime.md
Exec can be implemented as running additional containers.
For #345
> Remove exec from required runtime functionalities.

- README.md
> ReadMe: Link to shared Code of Conduct in TOB repo

- config.md
To match [where they're defined in the JSON Schema][1].  The old
location is from d4e7326d (config: JSON examples, 2016-04-06, #370),
and seems to have been accidental.
[1]: https://github.com/opencontainers/runtime-spec/blob/0982071b288ddddc1ae84d21c4bd682c96942f5c/schema/schema-linux.json#L21-L48
> config: Move (u|g)idMappings from 'process' to 'linux'

- bundle.md
- config.md
Closes #389
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>
> Remove requirement for rootfs path to be relative

- config-linux.md
- config.md
- schema/schema-linux.json
- specs-go/config.go
> Add support for Selinux mount context labels

- schema/schema.json
- specs-go/config.go
These were missed when we moved the field to Process struct.
> Fix remnants from SelinuxProcessLabel to SelinuxLabel rename

- .travis.yml
- Makefile
As we have several tools used in the Makefile, might as well make them
easier to install.
> Makefile: add target for tools

- config.md
- specs-go/config.go
And use “MAY” (RFC 2119) instead of “can” in the Markdown docs.
Otherwise:
$ ocitools generate --mount-cgroups=no --template <(echo {})
$ grep mounts config.json
"mounts": null,
> specs-go/config: Make Spec.Mounts omitempty

- config.md
"ociVersion ... must be in SemVer ... format" --> "ociVersion ... MUST be in SemVer ... format"
> [ Configuration | Version ] Capitalize MUST in ociVersion description

- config.md
"args" is an array of strings, not a string. 
Signed-off-by: Amit Saha <amitsaha.in@gmail.com>
> args is an array of strings

- config-linux.md
- config.md
To make it clear that the whole `linux` section is optional.
See discussion [here][1].
[1]: https://github.com/opencontainers/runtime-spec/pull/411/files/d57479d6f48fc50f584d566c26c9dc06da140946#r61618585
> config: Split platform-specific configuration into its own section

- runtime.md
"errors, if any, MAY be logged" --> "errors, if any, SHOULD be logged"
> [ Lifecycle ] Increase importance of logging errors

- .gitignore
- .tool/version-doc.go
- Makefile
Fixes #398
This produces a markdown page as a header for the PDF and HTML pages.
> version: include version in produced docs

- runtime.md
This slipped through the renumbering in 7117ede7 (Expand on the
definition of our ops, 2015-10-13, #225).
Signed-off-by: W. Trevor King <wking@tremily.us>
> runtime: Fix 'step 8' -> 'step 7' references

- config.md
The language from 15dee2e0 (runtime: Add prestart/poststop hooks,
2015-08-03, #34) landed well before we had glossary entries for the
runtime and container namespaces (from 5dad1255, config-linux: Specify
host mount namespace for namespace paths, 2015-12-18, #275).  Now that
we do have language to cover that concept, it's better to explicitly
say that hooks run in the runtime namespace instead of leaving it to
the reader to extrapolate from the filesystem requirement.
With the new namespace wording, the "host's filesystem" wording is
somewhat redundant.  I've left it in though, because I think it helps
to have a more gradual transition from hook paths to namespaces.
The most recent instance of reader uncertainty is [here][1].
[1]: …
> config: Explicitly put hooks in the runtime namespace

- Makefile
- config-solaris.md
- config.md
- schema/README.md
- schema/schema-solaris.json
- schema/schema.json
- specs-go/config.go
This PR introduces Solaris application container configuration parameters to OCI.
Signed-off-by: Abhijeeth Nuthan <abhijeeth.nuthan@oracle.com>
> Introducing Solaris in OCI

- README.md
This PR just adds a link to Solaris configuration in the README.md missed by initial PR,
"Introducing Solaris in OCI" , #411  
Signed-off-by: Abhijeeth Nuthan <abhijeeth.nuthan@oracle.com>
> Adding link in README.md to Solaris configuration.

- config.md
Change made with:
$ sed -i 's/\t/    /g' config.md
fixing tabs that were added with 1c49f4d2 (Add annotations and labels
to the Spec, 2016-03-04, #331).
> config: Use spaces (not tabs) to indent JSON

- specs-go/config.go
The spec requires UID and GID to be specified, so we shouldn't ignore if they are not specified.
Signed-off-by: Amit Saha <amitsaha.in@gmail.com>
> UID and GID for the main process are not optional

- Makefile
And use `command -v` instead of `which`.  Details in the commit messages.
> Makefile: Replace vbatts/pandoc with a PANDOC variable

- config.md
- specs-go/config.go
Also document `solaris` in the platform-specific configuration
section.  Details in the commit messages.
> specs-go/config: Make Linux and Solaris omitempty

- specs-go/config.go
It's an optional setting, and this change will fix the wordy:
$ ocitools generate --template <(echo '{}')
$ grep readonly config.json
"readonly": false,
Instead, `config.json` will not contain a `readonly` entry at all.
> specs-go/config.go: Make Root.Readonly omitempty

- specs-go/config.go
It's an optional setting, and this change will fix the wordy:
$ ocitools generate --template <(echo '{}')
$ grep terminal config.json
"terminal": false,
Instead, `config.json` will not contain a `terminal` entry at all.
> specs-go/config.go: Make Process.Terminal omitempty

- ROADMAP.md
This PR cherry-picks the first two from #423 and adds additional
target-removal commits with the reasoning I posted [to the list][1].
I'm happy to pull out any contentious and/or obvious commits into
separate PRs if that makes reviewing and landing this easier.
[1]: https://groups.google.com/a/opencontainers.org/forum/#!original/dev/pghr1WFU5KI/NDFTvMDiFAAJ
> ROADMAP: Remove stale targets (landed PRs, image-spec, ocitools, etc.)

- config.md
This should have been part of 759ee79c (config: Add platform-specific entry for 'solaris', 2016-05-06, #431), since the example has `platform.os` set to `linux`.
There was some (brief) [discussion][1] of this point before the `solaris` section landed, but the “should only be set if” wording landed in parallel via b373a15 (config: Split platform-specific configuration into its own section, 2016-05-02, #414), and I'd forgotten to go back and apply that logic to #411.
Having a full Solaris example would be useful, but I think it should be a separate, Solaris-only example.
[1]: https://github.com/opencontainers/runtime-spec/pull/411#discussion_r61621001
> config.md: Remove 'solaris' from full example

- runtime.md
This spec places RFC-2119 requirements on both bundles (bundle.md,
config.md, ...)  and runtimes (runtime.md, runtime-linux.md).  While
it's possible to envision a system where bundle validation is required
before container setup begins, it is also possible to decoupled
validation and allow the runtime to blindly stumble through as far as
it can.
We [already link to ocitools and OCT for testing both runtimes and
bundles][1], so users interested in pre-start validation can use those
tools.
This commit explicitly documents the non-requirement and links to
those tools, to make life less surprising for everybody.
This is the decoupled alternative to #404.
[1]: https://github.com/opencontainers/runtime-spec/blob/v0.5.0/implementations.md#testing--tools
> runtime: Explicitly allow 'start' to not validate config.json

- config.md
This was raised during reviews with folks working on Windows Containers.  
This squashes commits from PR #433
> [Config] Mount destinations MUST NOT be nested in Windows

- config.md
The old platform.os text had two MUST conditions.  The first could
have been read "the runtime MUST generate an error if invoked with a
config.json whose platform.os is incompatible with the host platform"
(which is the direction I'm going with this commit).  However, it
could also have been read "the bundle-validator MUST generate an error
if platform.os is incompatible with the content the bundle's other
content (e.g. 'linux' in platform.os, but only Windows binaries in the
bundle's rootfs).
For the second MUST, I doubt we want to require a compliant runtime
support all Go architectures itself.  And there is a benefit to
pointing runtime/bundle authors at the Go set, but not much benefit in
making that a hard limit (see opencontainers/image-spec#29 and
opencontainers/image-spec#60). …
> config: Clarify MUST for platform.os and .arch

- README.md
> Reference LICENSE file to keep consistency with others

- config.md
> Use RFC_2119 style for config.md

- runtime.md
The `Errors` section is more like a general description about
runtime, if it's a sub-section of `Operations`, it'll be hard
for both implementations and tests to define what this
`errors` operation really is.
> Move errors section out of operations

- runtime.md
Replace: https://github.com/opencontainers/runtime-spec/pull/447
> Clarify the operation is not for command-line api

- specs-go/config.go
This has been stale since cb2da543 (config: Single, unified config file, 2015-12-28, #284), when we dropped the attempt to distinguish between platform-independent and platform-dependent configuration.
This PR nibbles another commit off from #423 (which worked fairly well for #435).
> specs-go/config: Drop platform-independent comment

- config-linux.md
The user-namespace restriction isn't about the root filesystem in particular.  For example, if you bind mount in a second filesystem, the runtime shouldn't adjust ownership on that filesystem either.
I've also adjusted the old “permissions” to “ownership”, since that more clearly reflects the fields (user and group) that you would modify if you wanted to adjust for user namespacing.
This nibbles some more ground-work off from #423, since that approach worked well in #435.
> config-linux: Make “don't modify filesystem permissions” generic

- Makefile
In #428 I'd misunderstood vbatts/pandoc as a call to a locally-installed pandoc, when it's actually the name of a [Docker][1] [image][2].  With this series, we prefer a local pandoc if one exists, fall back to Docker and vbatts/pandoc if a local `docker` exists, and raise an error if neither `pandoc` nor `docker` exist.
This is an alternative to #440, which reverts dc9daf9e and doesn't allow for a locally-installed pandoc.
[1]: https://github.com/opencontainers/runtime-spec/pull/440
[2]: https://github.com/opencontainers/runtime-spec/pull/428#discussion_r63987603
> Makefile: Fix native pandoc invocation

- Makefile
https://github.com/opencontainers/runtime-spec/issues/454
> Makefile: prefer bash

- runtime.md
JSON is not a mandatory format, we should not use MUST
requirement on this.
> Remove one JSON related MUST requirement

- schema/schema.json
Use wording from config.md, since the JSON Schema doesn't seem like a
good place to be picking new words.
A tiny piece pulled out of #453, with wording that is copy/pasted from
config.md.
> schema/schema.json: Update path.root description

- .pullapprove.yml
Add PullApprove: https://pullapprove.com/opencontainers/runtime-spec/
Test for #457 
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Add PullApprove checks

- runtime.md
- splits `start` into `create` and `start`. Does not define `run` - that's an impl choice.
- `create()` is invoked to setup the container's NSs, cgroups, etc., but the user process is not yet started. The PID NS is created but paused waiting for the `start()` operation to be invoked. Control is returned to the caller.
- At this point any additional processing (e.g. pre-start hooks) can be invoked by the management/orchestration tooling.
- `start()` is invoked. The config.json's `process` property is used to start the user-defined process that is to be executed in the PID NS. Whether control is returned to the caller or not will depend on whether a `--detach` type of option was specified - so this is runtime dependent.
- The user-defined process will eventually stop - either by exiting or …
> Split create and start

- runtime.md
This wording is descended from 7117ede7 (Expand on the definition of
our ops, 2015-10-13, #225), but the idea is covered generically by
e53a72b (Clarify the operation is not for command-line api,
2016-05-24, #450), so we no longer need a create-specific note.
Especially in the lifecycle docs, where there's already enough going
on without this low-level detail.
> runtime: Drop create-specific API caveat from lifecycle

- runtime.md
Restore the line removed by be594153 (Split create and start,
2016-04-01, #384).  Without this, GitHub renders the list as a single
paragraph.
> runtime: Restore leading blank line before lifecycle list

- runtime.md
The shorter-than-normal (for the rest of this list) indent landed with
the line in be594153 (Split create and start, 2016-04-01, #384).
> runtime: Consistent indent for "However, some actions..."

- runtime.md
When thinking about kill() vs delete(), a client needs to know (gracefully - w/o errors) when to call each. Which means it needs to be able to query the container to know what its current state is (running vs stopped).  This defines a property in our 'state' struct to convey that info.
> Add a 'status' field to our state struct

- runtime-linux.md
Some fixes in runtime_linux.md, and added dev symbolic links.
It's adapted from:
https://github.com/opencontainers/runc/blob/master/libcontainer/SPEC.md
Addresses: opencontainers/runc#760
> Add dev symbolic links in runtime_linux.md

- schema/schema.json
The README title is:
Open Container Runtime Specification
And the config.md title is:
Container Configuration file
The JSON Schema covering that configuration file should have a description that combines those two titles without introducing new language.
More “bundle” sniping spun out from #423 / #453.
> schema/schema.json: Update main description

- specs-go/config.go
Proably needed to complete docker/docker#22922
Signed-off-by: Michael Holzheu <holzheu@linux.vnet.ibm.com>
> seccomp: Add ppc and s390x to specs-go/config.go

- Makefile
When this repo was only 'specs', then the generic name was not so bad.
But now there is also the oci-image-spec, so this lines up it's unique
name as well.
This also variablizes the output filename so it will be easier for
release specific names.
> Makefile: filename docs.* -> oci-runtime-spec.*

- runtime.md
The in-flight runC implementation just [fires][1] [a signal][2] at the
container.  It doesn't wait around to see if the signal has an
effect, or if it causes the container to crash, etc., etc.
[1]: https://github.com/opencontainers/runc/blob/28126f8039e226952d099f7376ba11cd9d00a59f/start.go#L29-L30
[2]: https://github.com/opencontainers/runc/blob/28126f8039e226952d099f7376ba11cd9d00a59f/libcontainer/container_linux.go#L253-L258
> runtime: Remove start's "fails to run" monitoring

- runtime.md
- specs-go/state.go
> Add annotations to the state json

- specs-go/state.go
Forgot to do this in previous PR.
> Add 'status' to state.go

- config-linux.md
- config.md
- runtime.md
- schema/defs-linux.json
- specs-go/config.go
The cgroup namespace is a new kernel feature available in 4.6+ that
allows a container to isolate its cgroup hierarchy. This currently only
allows you to hide information from /proc/self/cgroup. But I'm currently
working with upstream on expanding it so that you can modify your
hierarchy inside a user namespace (even a rootless container).
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> *: add support for cgroup namespace

- config.md
In the degenerate case where the container does not create a user
namespace, the "container namespace" distinction is unimportant, but
the phrasing is still accurate (the container and runtime namespaces
are the same).
> config: Explicit container namespace for uid, gid, and additionalGids

- ChangeLog
- specs-go/version.go
where ef1aa37acb7052e5b44948550fceb98ed94481a9 would be tagged `v1.0.0-rc1`
> Bump v1.0rc1

- config.md
This reverts commit 0f25f18b9b6dd315ba357d7f4f10d636474d7994 (#253).  Now that we're on to 1.0, we don't need to talk about 0.x.  And the lack of 0.x backwards compatability is covered by [SemVer 2.0 section 4][1]:
> Major version zero (0.y.z) is for initial development.  Anything may change at any time.  The public API should not be considered stable.
so removing the echo from our spec doesn't actually change anything.
[1]: http://semver.org/spec/v2.0.0.html
> Revert "Clarify backwards compatibility for major version 0"

- schema/schema.json
The JSON Schema requirement dates back to cdcabdeb (schema: JSON
Schema and validator for `config.json`, 2016-01-19, #313), but the
property has been explicitly optional in the Markdown spec since
7ac41c69 (config.md: reformat into a standard style, 2015-06-30).
Ping @vbatts.
> schema/schema.json: Make 'hostname' optional

- runtime.md
The indentation of the sub bullets for the status entries under State were not
indented by the 4 spaces required by markdown. They did not render well in
the pdf, at least with my native build with pandoc v1.13.2. Change them to 4
spaces, which now renders well.
Signed-off-by: Graham Whaley <graham.whaley@linux.intel.com>
> runtime.md: Fix sub-bullet indentation

- bundle.md
These distribution requirements belong in image-spec or similar.  They
don't apply to runtimes or filesystem bundles (the latter are covered
by the earlier "This MUST include the following artifacts"), which are
the two entities tested for compliance with this spec.
> bundle: Remove distribution references

- schema/README.md
Fix regression respectively introduced in 59ede1a and 59ede1a
The config-schema.json and state-schema.json references were missing "-schema".
> schema/README: Fix links to (config|state)-schema.json

- config-linux.md
- schema/defs-linux.json
The POWER and z architectures are part of libseccomp now and are included in the runc reference impl as well.
Signed-off-by: Phil Estes <estesp@gmail.com>
> Add new architectures from libseccomp 2.3.0

- specs-go/config.go
I'd added some omitempties in 5c2193f3 (specs-go/config: Make Linux and Solaris omitempty, 2016-05-06, #431), but it turns out to not have the intended effect unless the field is also a pointer type (even after I shifted the `omitempty` from the `platform` tag to the `json` tag ;).  Before this commit:
$ ./ocitools generate --template <(echo '{}')
$ jq . config.json
{
"ociVersion": "1.0.0-rc1-dev",
"platform": {
"os": "linux",
"arch": "amd64"
},
"process": {
"user": {
"uid": 0,
"gid": 0
},
"args": [],
"cwd": "/"
},
"root": {
"path": "rootfs"
},
"hooks": {},
"linux": {
"cgroupsPath": ""
},
"solaris": {
"cappedCPU": {},
"cappedMemory": {}
}
}
And after this commit:
$ ./ocitools generate --template <(echo '{}')
$ jq . config.json
{
"ociVersion": "1.0.0-rc1-dev",
"platform": {
"os": "linux", …
> specs-go/config: Make Linux and Solaris omitempty (again)

- README.md
On Thu, Jul 14, 2016 at 06:27:50PM -0700, Chris Aniszczyk [wrote][1]:
> There was a change in the phone number for the conference line, URL
> is the same.
>
> Join the call: https://www.uberconference.com/opencontainers
> Optional dial in number: 415-968-0849
> No PIN needed
Fixes #514.
[1]: https://github.com/opencontainers/runtime-spec/issues/514
> README: Update conference-call phone number

- config.md
This slipped through the rename in 2a5986f7 (schema/state-schema.json:
Add a JSON Schema for the state JSON, 2016-06-01, #481) and the first
round of fixes in dfb85b16 (schema/README: Fix links to
(config|state)-schema.json, 2016-06-13, #498).
Fixes #517.
> config: Update schema.json -> config-schema.json

- config-linux.md
This helps clear up some of the vagueness around cgroupsPath in the spec. It's
loosely modeled on what runC does (as well as allowing for custom cgroup
managers in runtimes). I also updated the cgroup section to make it clear that
lazy cgroup setup (where you only attach to the bare minimum of requested
cgroups) is allowed under the spec. This all originated from an IRC discussion
on #opencontainers.
This possibly obsoletes #270 (although that has some renaming going on).
Signed-off-by: Aleksa Sarai <asarai@suse.de>
/cc @opencontainers/runtime-spec-maintainers @wking
> config-linux: clarify cgroup requirements

- config.md
Also apply one sentence per line rule for list items.
> Rewrite mounts description in config.md

- GOVERNANCE.md
- RELEASES.md
https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/x-Oh3PDz1Y8
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Add governance and release process docs

- README.md
[Catch up][1] now that we're having 2pm meetings two weeks in a row.  There's also some earlier discussion [here][2].
[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/VlwOuGh2y84
[2]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/HXO-FplpEKM
> README: Change meeting time from 10am to 2pm Pacific

- config-linux.md
- specs-go/config.go
Both `linux.devices` and `linux.resources.devices`.  Details in the commit messages.
> config-linux: Make Linux 'devices' explicitly optional

- bundle.md
- config-linux.md
Change `file system` to `filesystem`
Signed-off-by: Lei Jitang <leijitang@huawei.com>
> Use filesystem instead of file system

- config.md
- runtime.md
- schema/config-schema.json
- schema/defs.json
- specs-go/config.go
- specs-go/state.go
Spun off from [here][1], this unifies the Markdown and Go comments for all of `Spec` except the `Linux` and `Solaris` entries, because it's better to not have to maintain different descriptions for the same idea.  The series also makes a few knock-on changes for consistency.
There seemed like enough was going on after making `Spec` consistent, so I'm postponing consistency for other Go types until after this lands.
This PR will conflict with a number of long-open PRs that have more complete fixes for some of these issues (e.g. opencontainers/runtime-spec#427), but those commits have mostly sat unreviewed for months, so I'm hoping the more restricted pivots here have a better chance of landing.  I can rebase any of the conflicted PRs (that I've submitted anyway) around this if/when it …
> config: Synchronize comments between Markdown and Go

- schema/config-linux.json
- schema/defs-linux.json
- schema/defs.json
Clearly, ignoring `"type": "object"` does not really break `validate`. 
However, currently we set `"type": "object"` in some object-type schemas, and ignore it in other object-type schemas.
This PR aims to make it consistent by adding the missing `"type": "object"`.
Signed-off-by: Haiyan Meng <haiyanalady@gmail.com>
> Add missing `"type": "object"`

- config-linux.md
Implement (b) from #537.  Also make it explicit that not listing a
namespace type will cause the container to inherit the runtime
namespace of that type.  More details in the commit message, although
that mostly summarizes the discussion from #537.
> config-linux: Extend no-tweak requirement to runtime namespaces

- specs-go/config.go
Found with:
$ git grep ' \*' origin/master -- specs-go/*.go | grep -v omitempty
origin/master:specs-go/config.go:       KernelTCP *uint64 `json:"kernelTCP"`
origin/master:specs-go/config.go:       ClassID *uint32 `json:"classID"`
Both settings are optional:
$ git grep '`kernelTCP`\|`classID`' origin/master
origin/master:config-linux.md:* **`kernelTCP`** *(uint64, optional)* - ...
origin/master:config-linux.md:* **`classID`** *(uint32, optional)* - ...
> specs-go/config: Make KernelTCP and ClassID omitempty

- README.md
- config-solaris.md
> Add language for compliance requirements around platforms

- Makefile
So we can use latest files after make clean.
> Remove code-of-conduct.md and version.md when clean

- schema/config-linux.json
- schema/defs.json
This should probably be part of our CI testing.
> schema: Run 'make fmt'

- README.md
> [ReadMe] Just one level/tier of compliance (rebase)

- config.md
Mimic https://github.com/opencontainers/image-spec/pull/164
and they should be kept in-sync
> Add text about extensions

- bundle.md
- config.md
- runtime.md
There's an outside change that these are intentional, since [I pointed one of these out earlier][1] and it wasn't fixed.  But I haven't seen ` : ` used intentionally outside of this project, and don't think we want to break ground in that direction ;).
[1]: https://github.com/opencontainers/runtime-spec/pull/510#discussion_r77291554
> Replace " : " with ": "

- .travis.yml
- Makefile
Add and update golang versions. Also fix install.tools target for
installing govet
> ci-tools: versions of golang

- config.md
> config.md: clarify the root filesystem path

- config.md
There are other APIs described in this specification (e.g. the state JSON format, and the [in-flight command-line API][1]), but this string covers the configuration file and referenced objects (e.g. the filesystem at root.path).  As additional, backwards compatible features are added to the spec (leading to 1.1, 1.2, etc. releases) and supported by runtimes, those runtimes will *still* stupport 1.0 configs.  Once a 2.0 spec is cut, runtimes that only support 2.0 (and nothing in the 1.0 line) will no longer support the 1.0 config.
My preferred approach here would be [to][2] [use][3] [JSON-LD][4] to explicitly document the intended semantics for each field, which would allow us to drop the config-wide version and version each field independently.  That would mean a breaking change on a …
> config: Clarify ociVersion covering the configuration <-> runtime API

- specs-go/config.go
These comments first landed in 820131db (*: flatten platform dependent source, 2016-03-08, #310).  But you can tell they're platform dependent by the platform:"..." tags.  The Go comment doesn't add any additional information.
Spun off from #564.
> specs-go/config: Drop "this field is platform dependent"

- config.md
- specs-go/config.go
Extracting pieces from the proof of concept PR for Windows OCI support at #504. This PR modified the `User` struct by fixing the description, adding a Windows-specific `user` field, and updating the documentation to include the changes, plus provide a sample JSON in the context of the `Process` structure.
> Windows: User struct changes

- config.md
> config: Quote whitespace in mount(8) links

- specs-go/config.go
We dropped these in #568 but #565 was developed in parallel and brought in a new one.
> specs-go/config: Drop "this field is platform dependent" (again)

- ChangeLog
- specs-go/version.go
https://groups.google.com/a/opencontainers.org/d/msg/dev/5qj2hATVxew/T9xFOcO-EAAJ
> Bump version 1.0.0 rc2

- README.md
To be consistent with opencontainers/image-spec.
> README: tweak title

- specs-go/config.go
Extracting pieces from the proof of concept PR for Windows OCI support at https://github.com/opencontainers/runtime-spec/pull/504. This PR tidies up the `Process` structure by putting annotations for platform support on `Capabilities`, `Rlimits` and `NoNewPrivileges`, none of which are used on `Windows`. In addition, it removes what appears to be an erroneous blank line that appeared to serve no purpose.
Note I'm assuming (probably incorrectly :innocent:) , that `Rlimits` and `NoNewPrivileges` are also relevant on `Solaris` too, but I'm not sure. If that is incorrect, I will update the PR to remove the `solaris` annotation.
> Platform annotations on `Process` struct

- config-linux.md
- config-solaris.md
- config.md
Make it clear that these are part of configuration compliance by using
the RFC 2119 keywords.
> config: Use REQUIRED and OPTIONAL for properties

- runtime.md
We [don't want to silently ignore settings that we understand but cannot implement][1] (we [*do* want to ignore settings that we don't understand][2], but that's a separate issue).
This raises a slightly sticky certification issue.  If a runtime *always* exits `create` with an error:
func create() err {
return fmt.Errorf("nope, I cannot create that container either.")
}
it would be neither complaint nor non-compliant.  It would not fail any MUSTs, but availing itself of the "cannot create the maintainer" option specified in this commit would mean the test suite could not test the deeper requirements around the config properties themselves.
So with this change, making Microsoft certifiable will still need an explicit weakening around root.path.  The easiest way to do that might be to have …
> runtime.md: Require 'create' to fail if config.json asks for the impossible

- README.md
@wking. Per https://github.com/opencontainers/runtime-spec/pull/563#issuecomment-248076957, this PR adds definitions for the words `unspecified`, `undefined` and `implementation-defined` to `README.md`, as per https://github.com/opencontainers/image-spec/pull/311.
> README: Define 'unspecified', 'undefined', and 'implementation-defined'

- config.md
- specs-go/config.go
Extracting pieces from the proof of concept PR for Windows OCI support at https://github.com/opencontainers/runtime-spec/pull/504. This adds the `consoleSize` platform specific field to the `Process` structure.
> config: Add consoleSize to process

- README.md
- config-windows.md
- config.md
- schema/README.md
- schema/config-schema.json
- schema/config-windows.json
- schema/defs-windows.json
- schema/defs.json
- specs-go/config.go
This adds Windows support to the OCI runtime-spec: code, JSON schema and markdown documentation. Note that the support has been added using 'aggressive namespacing', the matching changes of which for Linux and Solaris being currently out for review in https://github.com/opencontainers/runtime-spec/pull/567.
This is a formal follow-on the the previous proof-of-concept PR to add support for Windows, https://github.com/opencontainers/runtime-spec/pull/504
> Add support for Windows based containers

- specs-go/config.go
@wking As per comment https://github.com/opencontainers/runtime-spec/pull/504#r67990890 on the proof of concept PR for adding Windows support to the OCI runtime spec, this does the "aggressive namespacing" for all Linux and Solaris structures. Fortunately it doesn't change any of the JSON in the documentation, but will unfortunately have a big knock-on effect to downstream consumers of `config.go` through the `specs` package.
> Aggressive namespacing

- Makefile
golint [dropped support for Go 1.5][1].  See also opencontainers/runtime-tools#230.
[1]: https://github.com/golang/lint/commit/a428635c58fe96360e83667e2e1a8343fc292bf0
> Makefile: Require Go >= 1.6 for golint

- glossary.md
Pin down our JSON definition to a particular RFC (which we can explicitly bump if neccessary), instead of referencing the floating JSON homepage.
Explicitly make objects unordered and forbid duplicate names to avoid relying on unportable behavior.  RFC 7159 is [a bit more relaxed][1]:
> The names within an object SHOULD be unique.
but [warns][1]:
> An object whose names are all unique is interoperable in the sense
> that all software implementations receiving that object will agree
> on the name-value mappings.  When the names within an object are not
> unique, the behavior of software that receives such an object is
> unpredictable.  Many implementations report the last name/value pair
> only.  Other implementations report an error or fail to parse the
> object, and some implementations …
> glossary: Make objects explicitly unordered and forbid duplicate names

- config-linux.md
- runtime-linux.md
For consistency, while all other places use IO.
$ grep -rnIw IO * | wc -l
10
> Use IO instead of io

- config-linux.md
> Fix some typos

- runtime.md
Signed-off-by: Lei Jitang <leijitang@huawei.com>
> typo: fix missing `)`

- specs-go/config.go
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com
These items are defined as `required`, I'm not sure the history, but I think they should not be pointer type.
> specs-go/config: fix required items type

- config-linux.md
- specs-go/config.go
Basicly make the format consistent with others, no
semantics change.
Signed-off-by: Qiang Huang h.huangqiang@huawei.com
> Rewrite LinuxIDMappings

- config-linux.md
Related runc PR: https://github.com/opencontainers/runc/pull/1150
Signed-off-by: Zhang Wei zhangwei555@huawei.com
> Forbid duplicated namespaces with same `type`.

- config-linux.md
- config.md
Signed-off-by: Mrunal Patel mrunalp@gmail.com
> Clarify wording for terminal setting and /dev/console

- config.md
`destination` has been the path inside the container since #136.  My personal preference is to [have an explicit pivot root and allow paths relative to the current working directory][1], but that would be a big shift from the current OCI spec.  The only way the current spec lets you turn off the root pivot is by not setting a mount namespace at all (and even then, it's not clear if that turns off the pivot).  And the config's `root` entry is required (despite my [attempts to have it made optional][2]), so it's not really clear how containers that don't set a mount namespace are supposed to work (if they're supported at all).
You might be able to get away with something like:
> When a mount namespace is not set, `destination` paths are relative to the runtime's initial working directory …
> config: Require absolute mount destinations

- schema/defs-linux.json
This matches the config-linux.md spec which says these are both int64.
> schema: update major/minor types

- README.md
- config-linux.md
- runtime.md
This carries #578 and fixes some other format issues.
> Fix several format issues found by pdf and html

- config-linux.md
Matches the example in config.md
> [Config Linux] Consistent size values in example

- README.md
Also s/OpenContainers/OCI/ as used in the image-spec README.
> README: remove extraneous apostrophe

- specs-go/config.go
> spec-go/config: comment fix

- config.md
The shift happened in #574 and the `windows` entry landed in parallel with #573.  See also #617.
> config: Fix 'optional' -> 'OPTIONAL' for 'windows'

- config.md
The note is from #411, but as I [pointed out there][1], this is also true for Linux.  #412 landed in parallel with more explicit namepacing for these fields, so we no longer need the overly-specific Solaris note.
[1]: https://github.com/opencontainers/runtime-spec/pull/411#r61620322
> config: Drop Solaris UID/GID note

- README.md
Match the [recommendation in the RFC's abstract][1].  Also bump “keywords” → “key words” in the subsequent C99 sentence for consistency.
[1]: https://tools.ietf.org/html/rfc2119
> README: Use recommended RFC 2119 wording

- config.md
This happened in #574 but was accidentally rolled back in #518.
> config: Fix 'optional' -> 'OPTIONAL' for process.terminal

- README.md
- config.md
- glossary.md
- runtime.md
All of these sections are about configuration, and we don't usually use “{Whatever} configuration” in the headers.
Micro-pivot spun off from #489.
> config: Change “Process configuration” → “Process” header

- Makefile
This slash gets added back on (e.g. `$(OUTPUT_DIRNAME)/`) in all the places where a trailing slash matters.
> Makefile: Remove trailing slash from OUTPUT_DIRNAME value

- .gitignore
- Makefile
- README.md
- config-linux.md
- spec.md
First pass - and a little bit of extra clean-up.  Per the f2f at kubecon.
> Cleanup the spec a bit to remove WG/git text that's not really part of the spec

- config.md
- runtime.md
In #466, I'd proposed replacing our old “user-specified process” with “user-specified code” to help distinguish between `create` (cloning the container process) and `start` (signaling the container process to `execve` or similar the user-specified `$STUFF_FROM_THE_process_CONFIG`).  That PR was rejected, although the renaming proposed there had already landed via #462.
This PR attempts to find a common ground between “process” ([preferred][2] [by][3] [maintainers][4] in #466, but which I [consider incorrect][5]) and “code” (which [maintainers][6] [found][3] [confusing][4]).  The Linux `execve(2)` says “[program][7]” and unpacks that to “[a binary executable, or a script starting with a [shebang]][7]”.  proc(5) documents `/proc/[pid]/exe` by talking about “[the executed command][8]”.  The …
> *: Replace “user-specified code” with “user-specified program”

- specs-go/state.go
<del>
* `Root` is path to the container's rootfs which can be useful information
to hook, and the official sample runtime implementation--runc--has
already added this field as payload to hook, we should add this to the
spec.
* `Status` seems like unnecessary field, because `State` is payload to
hook and hook is executed in special time point, e.g.
1.  `Prestart` is a list of hooks to be run before the container process is
executed, indicating a status of `created`.
2. `Poststart` is a list of hooks to be run immediately after the container
process is started, indicating a status of `running`.
3. `Poststop` is a list of hooks to be run after the container process exits,
indicating a status of `stopped`.
So the `Status` field is redundant. 
</del>
According to definition of …
> Rename `version` to `ociVersion` according to runtime.md

- ChangeLog
- specs-go/version.go
https://groups.google.com/a/opencontainers.org/d/msg/dev/vm9laWGriwE/Ra-CE7MHDwAJ
d12da90 Merge pull request #633 from WeiZhang555/syncup-hook-state
9ce258d Merge pull request #629 from wking/code-to-program
7839cbb Merge pull request #626 from duglin/specCleanup
ee5a565 Merge pull request #621 from wking/output-dirname-trailing-slash
600b8b4 Merge pull request #619 from wking/tk/process-header
b69dcba Merge pull request #617 from wking/process.terminal-optional-case
780fc67 Merge pull request #622 from wking/rfc-2119-wording
44c6543 Merge pull request #623 from wking/no-solaris-uid-gid-note
f6b9850 Merge pull request #624 from wking/windows-optional-case
176fe80 Merge pull request #625 from Mashimiao/spec-config-comment-fix
d7e87ca Merge pull request #627 from jonboulle/master
cc983bb …
> Version bump for v1.0.0-rc3

- runtime-linux.md
> [Runtime Linux] Add anchor tags for headings

- principles.md
> [Principles] Add anchor tags for headings

- config-windows.md
> [Config Windows] Add anchor tags for headings

- runtime.md
> runtime: Fix config.md -> config.json typo

- bundle.md
> [Bundle] Adds anchor tags for headings and bullets

- config.md
- schema/config-schema.json
- specs-go/config.go
And make it omitempty, otherwise:
```
$ ocitools generate --template <(echo '{}')
$ cat config.json | jq -S .
{
"hooks": {},
...
}
```
To provide space for the type information and `optional`, I've shuffled the hook docs to follow our usual:
```
* **`{property}`** ({type}, {when-needed}) {notes}
```
format.  I've kept the separate event-trigger sections (e.g. `### Prestart`) since they go into more detail on the timing, purpose, and exit handling for the different events (and that seemed like too much information to put into the nested lists).
This may be unnecessary if #384 kills hooks, although:
1. I'm not sure if the `run` command will keep hooks, and
2. The current #384 tip [still has these hook docs](https://github.com/opencontainers/runtime-spec/blob/0430aaf1dc22da65b66c28e8ba7ffb5ed …
> config: Explicitly list 'hooks' as optional

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
Carry #499
For these values, cgroup kernal APIs accept -1 to set
them as unlimited, as docker and runc all support
update resources, we should not set drawbacks in spec.
> Allow negative value for some resource fields

- config.md
Alternative of #583 , as what we do for `namespaces`
in #597 .
> Forbid duplicated rlimits with same type

- schema/config-linux.json
- schema/config-schema.json
- schema/defs-linux.json
- schema/defs.json
- specs-go/state.go
> Perfect json content

- ROADMAP.md
- config-linux.md
- config.md
This restriction originally landed via #158.  The hostname case landed via #214, citing the namespace restriction.  The restriciton extended to runtime namespaces in #538.  There was also a proposal in-flight to get config-wide consistency around the no-tweaking concept (#540).
In today's meeting, the maintainer consensus was to [strike the no-tweaking restriction][2], which is what I've done here.  I've removed the ROADMAP entry because this gives folks a way to adjust existing containers (launch a new container which joins and tweaks the original).
The hostname entry still mentions the UTS namespace to provide a guard against accidental foot-gunning.  There was no no-tweaking language for properties related to other namespaces (e.g. 'mounts').  Maybe the other namespaces have more …
> config-linux: Lift no-tweaking namespace restriction

- config-linux.md
I think runtime should generate an error, if devices has duplicated device path.
Because we don't know which one is really needed.
Signed-off-by: Ma Shimiao <njmiaoge@126.com>
> config-linux: Add restriction for duplicated device path

- config.md
empty key does not make any senses, we should limit it.
> config.md: add empty limit for key of annotations

- schema/defs.json
int64Pointer is used in config-linux.json, but hasn't been defined.
> defs.json: add misssing int64Pointer

- specs-go/config.go
An empty string works as null value for strings so we don't need string pointers.
> Remove string pointers

- schema/config-linux.json
- schema/defs-linux.json
- schema/defs.json
- style.md
And update the style guide to catch up with #653.
> schema: Remove string pointers

- config.md
This PR is [my suggestion][1] from #645, which @dqminh thumbs-upped, but which didn't make it in before #645 landed.
Pull the empty-key restriction out into its own sentence (instead of leaving it in the middle of the uniqueness restriction).
Drop the “best practice” portion, because the following line is “Keys SHOULD be named using a reverse domain notation…”, which covers that idea more explicitly.
[1]: https://github.com/opencontainers/runtime-spec/pull/645/files#r94497998
> config: Bring "unique... within this map" back together

- schema/README.md
- schema/validate.go
And only fall back to assuming they're a local file if they don't
already contain :// (which is unlikely to show up in local paths).
This makes it easy to validate configurations against different
versions of the JSON Schema (e.g. v0.5.0 or v1.0.0-rc1).
Ping @vbatts.
> schema/validate: Allow schema identifiers to contain a URL scheme

- schema/config-linux.json
- schema/defs-linux.json
> schema: fix items based on latest spec

- README.md
And add a header for the Table of Contents.
Spun off from #570.
> README: Consistent header nesting

- runtime.md
[proc(5)](http://man7.org/linux/man-pages/man5/proc.5.html) describes the following state entries in
`proc/[pid]/stat` (for modern kernels):
- R Running
- S Sleeping in an interruptible wait
- D Waiting in uninterruptible disk sleep
- Z Zombie
- T Stopped (on a signal)
- t Tracing stop
- X Dead
and [ps(1)](http://man7.org/linux/man-pages/man1/ps.1.html) has a bit more context (for modern kernels):
- D uninterruptible sleep (usually IO)
- R running or runnable (on run queue)
- S interruptible sleep (waiting for an event to complete)
- T stopped by job control signal
- t stopped by debugger during the tracing
- X dead (should never be seen)
- Z defunct ("zombie") process, terminated but not reaped by its
parent
So I expect "stopped" to mean "process still exists but is paused,
e.g. by …
> runtime: Replace "process is stopped" with "process exits"

- schema/config-linux.json
- schema/defs-linux.json
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com
> fix blkio related validation

- runtime.md
Because during creation (before `created`) we may not have a container process yet (e.g. if we're still reading the configuration or setting up cgroups), and in the `stopped` phase the PID is no longer meaningful.
Also add OPTIONAL/REQUIRED and remove colons for consistency with the `config.md`.
This documents (as best I can tell) the current semantics and gives #459 / #661 a well-defined REQUIREment to relax.
It's also the tip commit from #507 (currently at 08d52a0) cherry-picked onto master.
> runtime: Only require 'pid' in the state for created/running statuses

- .travis.yml
- Makefile
Work around travis-ci/travis-ci#4596 until that is fixed upstream.
This avoids pulling in commits from the base tip that aren't reachable
from the head tip (e.g. if master has advanced since the PR branched
off, and the PR is against master).  We only want to check commits
that are in the head branch but not in the base branch (more details
on the range syntax [here](http://git-scm.com/docs/gitrevisions#_specifying_ranges)).
Once the Travis bug does get fixed, the shell replacement will be a
no-op.  So we don't have to worry about checks breaking once the bug
gets fixed, and can periodically poll the bug and remove the
workaround at out leisure after the fix.
Spun off from #182 now that #215 has landed.
> .travis: Convert TRAVIS_COMMIT_RANGE base...head to base..head

- config-linux.md
change MUST to SHOULD so containers are not required to have all these filesystems mounted.
Related to discussions in https://github.com/opencontainers/runc/pull/1176
cc @cyphar @crosbymichael @philips @justincormack
> linux: relax filesystem requirements for container

- schema/config-linux.json
- schema/config-windows.json
- schema/defs-linux.json
- schema/defs-windows.json
- schema/defs.json
Maintainers feel (and I agree) that there's [no point in explicitly allowing a null value when callers can simply leave the property unset][1].  This commit removes all references to “pointer” and “null” from the JSON Schema to support that decision.  While optional properties [may sometimes be represented as pointer types in Go][2], optional properties should be represented in JSON Schema by not including the properties in the `required` array.
Spun off from [this comment][3] as [requested][4] by @RobDolinMS.
[1]: https://github.com/opencontainers/runtime-spec/pull/555#issuecomment-272020515
[2]: https://github.com/opencontainers/runtime-spec/blob/c368be6a74d7383f9b6c9a4b7a3e73d65537b08a/style.md#optional-settings-should-not-have-pointer-go-types
[3]: …
> schema: Drop pointers and nulls

- runtime.md
- schema/state-schema.json
- specs-go/state.go
The path part is just redundant and runc is already providing `bundle` to consumers. 
> Rename bundlePath to bundle

- ChangeLog
- specs-go/version.go
`git log --oneline --merges v1.0.0-rc3...7b10218 | awk '{ print $5 }' | wc -l`
#216
#664
#545
#665
#465
#660
#650
#655
#490
#654
#656
#653
#652
#645
#647
#649
#646
#607
#648
#427
#612
#643
#637
#639
#636
#640
#638
#642
> Bump version for 1.0.0-rc4

- config.md
Some minor narrative nits cleaned up in support of resolving issue #303. Most changes attempt to make it clear that multiple platforms are supported but keep the Linux examples and references in place. In the Process section, Linux-only options were left under the original header, anything which is supported by at least one other platform was pulled out.
> narrative cleanup in support of Base Config Compatibility #303

- schema/validate.go
add usage message to validate:
'cat document.json | validate schema.json'
validate would block in such case:
'validate schema.json'
add stdin status check to avoid this.
Signed-off-by: Deng Guangxing dengguangxing@huawei.com
before:
```
$ ./validate config-schema.json 
^C$
```
after:
```
$ ./validate config-schema.json 
Error: document.json not specified
Usage:
./validate <schema.json> <document.json>
or
cat <document.json> | ./validate <schema.json>
```
> improve validate usage message

- runtime.md
To distinguish between "we're still setting this container up" and
"we're finished setting up; you can call 'start' if you like".
Also reference the lifecycle steps, because you can't be too explicit
Also relax the `pid` requirement from “always” to “only for `created`
and `running`”.  During the `creating` phase we may not have a
container process yet (e.g. if we're still reading the configuration
or setting up cgroups), and in the `stopped` phase the PID is no
longer meaningful.
Some discussion with @mikebrow around this starting [here](http://ircbot.wl.linuxfoundation.org/eavesdrop/%23opencontainers/latest.log.html#t2016-06-23T20:00:17).
This PR builds on #465, so that should get reviewed first.
> runtime: Add 'creating' to state status

- config.md
- spec.md
Spun off from [here](https://github.com/opencontainers/runtime-spec/pull/564#issuecomment-247344440).
More details on the individual pivots in the commit messages.  The
meat is the one-liner in the last commit, and the bit I'm not sure
about (also discussed in the commit message ;) is whether we want to
rename the JSON tag from `platform:"…"` to `protocol:"…"` to
consolidate around the “protocol” term used in #527 to [decouple
compliance from platforms](https://github.com/opencontainers/runtime-spec/pull/527#issuecomment-238979250).  For example, if we want to add
optional extensions (e.g. allowing Linux containers that use
namespacing but not cgroups), we could have a ‘linux’ protocol (with
the base stuff) and a ‘linux-cgroups’ protocol (with the cgroups stuff
and the base stuff). …
> config: Link platform:"…" JSON tags with ~~protocol~~ platform slugs

- config.md
- schema/defs.json
> config.md: args of Hooks should be optional

- spec.md
> Add OCI Runtime Abstract

- schema/defs-linux.json
When type is p, major and minor is not required.
So, we should not leave them in required.
> schema: remove major,minor from device required items

- config.md
- schema/config-schema.json
- schema/defs-linux.json
- specs-go/config.go
> Add ambient and bounding capability support

- config-linux.md
> Remove uid/gid mapping limit depend on kernel

- config-linux.md
- config.md
- schema/defs-linux.json
- specs-go/config.go
I'm opening this to continue [this discussion](https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/BkTgy0bZrXQ) about improving the seccomp specification. @mrunalp @runcom @justincormack
While of course runtime-spec shouldn't make changes with specific projects in mind, it's worth noting that this format is currently being used in [cri-o]() and [docker]().
The change proposes that Syscalls be grouped together in the case that their listings be exactly the same. Conditionals can be expressed on architectures and capabilities also. Comments are a nice feature for dev-ops teams as well.
There's inconsistencies ([example](https://github.com/opencontainers/runc/issues/1273)) in the use of seccomp specifications across oci projects, I think heading in the direction of this …
> config: Improve seccomp format to be more expressive

- schema/config-schema.json
Signed-off-by: zhouhao zhouhao@cn.fujitsu.com
> Fix config-schema.json

- config.md
- schema/defs.json
- specs-go/config.go
These are optional on multiple platforms and should be left up to the
runtime/host system for validation.
Closes #470
> Make mount type and source optional

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
This partially revert #648 , after a second thought, I think we
should use specs value the same as kernel API input, see:
https://github.com/opencontainers/runtime-spec/issues/692#issuecomment-281889852
For memory and hugetlb limits *.limit_in_bytes, cgroup APIs take the values
as string, but the parsed values are unsigned long, see:
https://github.com/torvalds/linux/blob/v4.10/mm/page_counter.c#L175-L193
For `cpu.cfs_quota_us` and `cpu.rt_runtime_us`, cgroup APIs take the input
value as signed long long, while `cpu.cfs_period_us` and `cpu.rt_periof_us`
take the input value as unsigned long long.
> Set specs value the same as kernel API input

- config-linux.md
- config.md
- implementations.md
- project.md
- runtime.md
- spec.md
- style.md
This PR adds anchor tags to remaining files. 
Closes #634
> Anchor tags

- config.md
- runtime.md
Details in the commit messages.
Instead of making these changes in a fresh commit off master:
```
o---o---o  master
\
o  tk/restore-hook-lifecycle
```
I've made them in two merges so `git blame` can tell that some lines come from historical commits, and that I'm just pulling them out of the history.  The structure of this branch is:
```
a---c---o---o  master
\ x         \
b-d---------e  tk/restore-hook-lifecycle
```
where `b` is #384, `c` is #384 landing, and `d` and `e` are new for this PR.
> Restore hook language removed by create/start split

- README.md
- ROADMAP.md
- bundle.md
- config-linux.md
- config-solaris.md
- config.md
- glossary.md
- implementations.md
- project.md
- runtime-linux.md
- spec.md
- style.md
Some hopefully useful link cleanup throughout the specification. Closes #676
Signed-off-by: Jesse Butler <jesse.butler@oracle.com>
> make link usage consistent across the specification

- MAINTAINERS
> Remove lk4d4 as maintainer

- config-solaris.md
Unwind an overly-aggressive backtick replacement from #687.
> config-solaris: Fix "VNIC`s" -> "VNIC's" typo

- style.md
These are literal quotes, and we don't want Markdown to confuse the underscores with [emphasis delimiters][1].
[1]: http://daringfireball.net/projects/markdown/syntax#em
> style: Backtick `DOC_FILES`, `_N`, and `N`.

- config.md
Fix a JSON typo which snuck in with #675.
> config: Remove trailing comma in CAP_KILL examples

- schema/defs-linux.json
The:
"type": [
"string"
]
syntax added in #657 is not valid:
$ ./validate ./config-schema.json <../config.json
The document is not valid. see errors :
- linux.seccomp.syscalls.0.names: Invalid type. Expected: string, given: array
> schema/defs-linux: Fix type for seccomp names

- config-linux.md
- config.md
- specs-go/config.go
> remove comment

- config-linux.md
- specs-go/config.go
Add support for Intel Resource Director Technology (RDT) / Cache Allocation
Technology (CAT). Add L3 cache resource constraints in Linux-specific
configuration.
This is the prerequisite of this runc proposal:
https://github.com/opencontainers/runc/issues/433
For more information about Intel RDT/CAT, please refer to:
https://github.com/opencontainers/runc/issues/433
Signed-off-by: Xiaochen Shen <xiaochen.shen@intel.com>
> specs-go/config: add Intel RDT/CAT Linux support

- config-linux.md
> config-linux.md: clearly require absolute path for namespace

- config.md
> config.md: fix broken links

- spec.md
> spec.md: small fix

- specs-go/config.go
> specs-go/config.go: format code

- config.md
The `key: value` syntax is for objects, but `mounts` is an array.
> config: Fix broken JSON in Windows mount example

- config-linux.md
> config-linux.md: fix seccomp

- .gitattributes
- README.md
- meeting.ics
Re-submitting #719, since we've decided that we're ready for it now (I think), and there [seem to be problems with re-opening that PR][1].  Lots of details on the commit in the commit message, the #719 discussion, and the [list thread][2] for folks who are interested.
[1]: https://github.com/opencontainers/runtime-spec/pull/719#issuecomment-288742851
[2]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/p0mTOspVgd0
> README: Document the alternate-week meeting times

- config-linux.md
- config.md
We have a few different element types in our arrays, so it's useful to clarify the element type for the property being specified.  Before this commit:
$ sed -n 's|.*\*\*`\([^`]*\)`\*\*[^(]*(\([^,]*\),.*|\2|p' *.md | sort | uniq -c | grep array
7 array
1 array of ints
8 array of objects
13 array of strings
All of the bare `array` instances turned out to be arrays of objects.
> *: Replace "array" type with "array of objects"

- README.md
And fix a period/paren swap.  The period/paren swap and contry-code addition both bring the local version more in line with [the image-spec version][1] and seem like good changes.
I've diverged from the image-spec version by using space separation in the phone number instead of hyphens.  From [E.123][3]:
> 9.1  Grouping of digits in a telephone number⁵ should be accomplished by means or spaces⁶ unless an agreed upon explicit symbol (e.g. hyphen) is necessary for procedural purposes. Only spaces should be used in an international number.
[1]: https://github.com/opencontainers/image-spec/blob/v1.0.0-rc5/README.md#weekly-call
[3]: https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-E.123-200102-I!!PDF-E&type=items
> README: E.123 number for meeting call

- README.md
@RobDolinMS had been keeping the wiki up to date with links to the MeetBot logs, but linking directly to the MeetBot logs gives us one less thing to maintain.  The meetings which are only in the wiki are 2015-07-22, 2015-08-05, 2015-08-12, 2015-08-26, 2015-09-02, 2015-09-09, 2015-09-16, 2015-09-24, 2015-09-30.  The last is in MeetBot, but it was our first MeetBot meeting, so the MeetBot logs are not great.
> README: Link to MeetBot logs for meeting minutes

- meeting.ics
And bump `DTSTAMP` for the touched `VEVENTS`.
This is less DRY, but makes life easier for folks pulling up the calendar a minute before the meeting, since they don't have to click through to the README section.  Also [requested][1] by @vbatts ;).
The [`LOCATION`][2] entry seems like a reasonable location for the conference-call page, so I've used that.  Note that the URI there is a text value; `LOCATION` [supports URIs in `ALTREP`][2], but the UberConference page isn't an “[alternate text representation for the property value][3]”.  The URI in `DESCRIPTION` is a fallback for clients that don't support/display `LOCATION` (I'm not sure if any exist, but it's easy to play it safe).  I couldn't find a more structured location for the phone number, unless we also wanted to put that in …
> meeting: Add UberConference information

- meeting.ics
And bump `DTSTAMP` for the touched `VEVENTS`.
com.android.calendar version 7.1.1 only displays the `DESCRIPTION` body, and does not provide a link to `ALTREP` (in fact, I don't see any instances of `ALTREP` in [the source][1]).  Including the README link in the `DESCRIPTION` body gives folks using that calendar application an easy way to get to the README section.
The ICS was validated [here][2].
This will conflict with #757.  There's already one LGTM there, so I suggest landing that one first.  However, I'm happy to rebase whichever PR lands second.
[1]: https://android.googlesource.com/platform/packages/apps/Calendar/+/android-7.1.1_r38
[2]: https://icalendar.org/validator.html
> meeting: Include README link in DESCRIPTION body

- schema/Makefile
Signed-off-by: zhouhao zhouhao@cn.fujitsu.com
> schema: modify Makefile

- specs-go/config.go
It used to have this, but the `omitempty` [was][1] [dropped][2] in #657.  However, the docs that landed in #706 [list the property as optional][3], and if it is optional, we can leave it unset instead of serializing an empty array.
If it should be required, then we should also require it to have a minimum length of 1 (#762).
Ping @GrantSeltzer, @q384566678.
[1]: https://github.com/opencontainers/runtime-spec/pull/657/files#diff-7f24d60f0cbb9c433e165467e3d34838L534
[2]: https://github.com/opencontainers/runtime-spec/pull/657/files#diff-7f24d60f0cbb9c433e165467e3d34838R534
[3]: https://github.com/opencontainers/runtime-spec/pull/706/files#diff-428eec4013a655816cdefafd5d3505f1R543
> specs-go/config: Add omitempty to LinuxSyscall.Args

- spec.md
Catching up with [erratum 499][1].
[1]: https://www.rfc-editor.org/errata_search.php?rfc=2119&eid=499
> spec: Add "NOT RECOMMENDED" to RFC 2119 keywords

- config.md
This is pretty clear from the examples like [this][1]:
"consoleSize": {
"height": 25,
"width": 80
}
But examples are not normative, so this commit makes the character units normative.
[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config.md#L180
> config: Specify height/width units (characters) for consoleSize

- schema/Makefile
> schema: add `clean` to Makefile

- config-linux.md
This was broken by #687, which updated the link label, but not this link.  Now that the link label matches the link text, we can use the [implicit link name shortcut][1].
[1]: https://daringfireball.net/projects/markdown/syntax#link
> config-linux: Fix 'file' POSIX link

- config-linux.md
According to the  [shared subtree](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt).
> config-linux.md: Increase the valid value of rootfsPropagation

- config-linux.md
- config-windows.md
- schema/config-linux.json
- schema/defs-linux.json
- schema/defs-windows.json
- specs-go/config.go
> Remove range limit which depend on kernel

- schema/Makefile
The only non-phony target (where the target name matches the output file) is `validate`, but we need `.PHONY` there because the Go dependencies are not represented in the `Makefile`.  This commit adds the missing `.PHONY` declarations to the other targets, which truly are phony.
Spun off from [this discussion][1] and following the example set by [the `clean` entry in the main `Makefile`][2].
[1]: https://github.com/opencontainers/runtime-spec/pull/774#discussion_r112252004
[2]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/Makefile#L97-L98
> schema/Makefile: Add .PHONY declarations for phony targets

- config-linux.md
- schema/defs-linux.json
I expect the (undocumented) intention here is to iterate through `names` and call `seccomp_rule_add(3)` or similar for each name.  In that case, an empty `names` makes the whole syscall entry a no-op, and with this commit we can warn users who are validating such configs.
If, on the other hand, we were comfortable with no-op syscall entries, we'd want to make `names` OPTIONAL.
Warning folks who accidentally empty (or don't set) `names` seems more useful to me, and doesn't restrict the useful config space, so that's what I've gone with in this commit.
`minItems` is documented [here][1], and there is an example of its use [here][2]:
```
"options": {
"type": "array",
"minItems": 1,
"items": { "type": "string" },
"uniqueItems": true
},
```
[Part][3] of #762.
[1]: …
> config-linux: Require at least one entry in linux.seccomp.sycalls[].names

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
Fixes #762, since the issue there has been quiet, and [1.0 may be almost upon us][1], so I'm nervous about leaving the issue to cook for too long ;).
This commit has gone with OPTIONAL, because a seccomp config which only sets `defaultAction` seems potentially valid.  But I'd be ok with the “REQUIRED with length > 0” approach to fixing #762 too.
[1]: http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2017/opencontainers.2017-04-12-14.59.log.html#l-13
> config-linux: Make linux.seccomp.syscalls OPTIONAL

- schema/config-linux.json
- schema/defs-linux.json
> schema: Add enumeration to rootfsPropagation values

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
In order to increase the granularity of CPU resource control, change the CPU Percent (0-100) resource setting to CPU Maximum (0-10000)
The HCS API accepts a ProcessorMaximum, which is a percentage multiplied by 100. This PR allows finer control over the CPU resources of Windows containers by extending the ProcessorMaximum into the OCI spec, rather than truncating to a 0-100 percent.
The discussion context is https://github.com/moby/moby/issues/32014 and https://github.com/moby/moby/pull/32608. The implementation of NanoCPUs in Moby should be able to scale to precision smaller than a single percent of total CPU resources.
/cc @jhowardmsft 
Signed-off-by: Darren Stahl <darst@microsoft.com>
> Change Windows CPU Percent to Maximum

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
Windows does not have a memory reservation in the platform. This removes the field from the runtime spec.
Signed-off-by: Darren Stahl <darst@microsoft.com>
> Remove Memory reservation on Windows

- specs-go/config.go
> Remove range limit

- schema/config-linux.json
- schema/config-windows.json
- schema/defs-linux.json
- schema/defs-windows.json
> schema: bug fixes

- config-linux.md
So we can compliance-test runtimes for these settings.
Also remove the tutorial, since the kernel docs should provide sufficient documentation on that front.  The kernel can be patched if they do not, and we do not include tutorials for other config-linux settings in this spec.
See also opencontainers/runC#433 and opencontainers/runC#1279.
CC @xiaochenshen.
> config-linux: RFC 2119 wording for intelRdt

- config-solaris.md
> config-solaris.md: fix info

- config-linux.md
The previous wording hinted at, but did not require, this setting to be implemented via `oom_score_adj`.  With the new wording, when proc is mounted at `/proc`, the container process can check this value by looking at `/proc/self/oom_score_adj`.
Part of #746.
> config-linux: RFC 2119 wording for oomScoreAdj

- config.md
- schema/defs.json
If the timeout value was zero, the hook would always error, and there doesn't seem to be much point to that.  And I'm not sure what negative timeouts would mean.  By adding this restriction, we do not limit useful hook entries, and we give the validation code grounds to warn users attempting to validate configs which are poorly defined or have useless hook entries.
Removing the pointer is not strictly required, but keeps up with our [anti-pointer zero-value style][1] now that Go's zero-value is clearly invalid.
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/style.md#optional-settings-should-not-have-pointer-go-types
> config: Require strictly-positive timeout values

- config.md
Because:
1. This section defines the configuration format, and doesn't need to be tied to a particular filename.
2. The bundle spec (in `bundle.md`) already has:
> This REQUIRED file MUST reside in the root of the bundle directory and MUST be named `config.json`.
The config.md line may have been useful when it was added (77d44b10).  But since the bundle.md line landed in 106ec2da (#210), I think it's been redundant.
> config: Drop the redundant config.json filename requirement

- specs-go/config.go
Avoid injecting `"consoleSize":{"height":0,"width":0}` when serializing with Go's stock JSON serializer.  Using a pointer for this optional struct property works around golang/go#11939.
Spun off from #759.
> specs-go/config: Use a pointer for Process.ConsoleSize

- config.md
Instead of leading off with links to a bunch of other places, notes on the Go tags, etc., make things more inviting by leading off with a big-picture summary of what the configuration is about.
Also drop the `config.json` existence MUST because:
1. This section defines the configuration format, and doesn't need to be tied to a particular filename.
2. The bundle spec (in `bundle.md`) already [has][1]:
> This REQUIRED file MUST reside in the root of the bundle directory and MUST be named `config.json`.
The `config.md` line may have been useful when it was added (77d44b10).  But since the `bundle.md` line landed in #210, I think it's been redundant.
[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/bundle.md#L14
> config: Lead off with the purpose of the config

- config.md
With the same link update that config-solaris.md got in #786, since the old link 404s.
> config: Update zonecfg(1M) link to match config-solaris.md

- runtime.md
This wording landed without comment as part of #225.  However, I'm not entirely clear on the exception it's making.  It may be trying to say something like:
> Just because you were authorized to manage that container when you created it doesn't mean you're still authorized to perform operation X on it now.  Maybe you've lost privileges in the meantime.
But as far as compliance testing is concerned, the same test harness will be calling `create` and the subsequent operations.  That harness will be reporting MUST violations if the runtime refuses a subsequent operation, and removing the access-control loophole makes it more obvious that the runtime's refusal is non-compliant.
> runtime: Drop "Barring access control concerns"

- config-linux.md
- config.md
- schema/config-linux.json
- schema/config-schema.json
- specs-go/config.go
The only discussion related to this is in #236 and #292, where the relationship between `oomScoreAdj` and `disableOOMKiller` is raised.  But since #137 resources has been tied to cgroups, and `oomScoreAdj` is not about cgroups. We [currently have][1]:
> You can configure a container's cgroups via the resources field of the Linux configuration.
In #782, I suggested we move the property from `linux.resources.oomScoreAdj` to `linux.oomScoreAdj` so config authors and runtimes don't have to worry about what `cgroupsPath` means if the only entry in `resources` is `oomScoreAdj`.  @crosbymichael [responded with][2]:
> If anything it should probably go on the process
So that's what this commit does.
Fixes #782.
[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config-linux.md#L18 …
> config: Shift oomScoreAdj from linux.resources to process

- config-solaris.md
These were added in #687 to follow the new [`_N` name-dedup policy][1] (vs. [the `config.md` target][2]).  They were just removed in #786 ([overlooking that policy][3]?).  This commit brings them back.
[1]: https://github.com/opencontainers/runtime-spec/blame/101e6f9d5c32579c245d8f45f4bdcd87f9a40cf9/style.md#L35
[2]: https://github.com/opencontainers/runtime-spec/blame/101e6f9d5c32579c245d8f45f4bdcd87f9a40cf9/config.md#L838
[3]: https://github.com/opencontainers/runtime-spec/pull/786#discussion_r115532596
> config-solaris: Restore 'zonecfg.1m_2' link targets

- README.md
- config.md
- specs-go/config.go
> small typo fix

- config-linux.md
> config-linux: make interface name clear

- config-linux.md
This is my suggested alternative to #729, which is currently removing the lowercase “required” but keeping the redundant MUST.  Any runtime which violated the MUST would necessarily violate some more specific constraint on a `resources` setting, so this PR removes the MUST entirely.
> config-linux: Remove redundant MUST for minimum cgroup controllers

- config-linux.md
- style.md
Since #687, the official style is to [only use reference-style links for external links][1].  I expect the remaining three entries just slipped through.  This commit adjusts everything found with:
$ git grep ']: [a-z]' | grep -v http
It also fixes the underscore → hyphen in the `glossary.md#container-namespace` target and updates the `capabilities` location to catch up with #329.
[1]: https://github.com/opencontainers/runtime-spec/blob/f56fe8ba78f9d70c63fbd301cf1cd680218742fa/style.md#links
> *: Use inline links for remaining internal references

- config.md
Opening this as we discussed on our review call today.  The intent here is to _not_ have an explicit list of "string to kernel constant" mappings in the specification, and to instead expect implementations to make a reasonable effort to have up-to-date mappings (especially for kernel features that might be newer than the particular specification release), and to error out for anything that they can't map.
As I mentioned on the call, I do not feel that this is a "1.0 blocker" -- the existing language is sufficient in my eyes to get the point across to implementors what they're expected to do.
> config: strengthen punt to kernel for valid "capabilities" strings

- config-linux.md
Previously we had no MUST-level runtime requirements for namespace entries in valid configs.  This commit attempts to pin those down.  For more background on hierarchical namespaces, see [here][1].  For more background on the owning user namespace idea, see [here][2], [here][3], and [here][4].
The “`path` not associated with a namespace of type `type`” condition ensures that runtimes don't blindly call `setns(2)` on the path without setting `nstype` nonzero.
Part of #746.
Ping @cyphar, especially on the owning-user-namespace condition.
[1]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a7306ed8d94af729ecef8b6e37506a1c6fc14788
[2]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6786741dbf99e44fb0c0ed85a37582b8a26f1c3b
[3]: …
> config-linux: RFC 2119 tightening for namespaces

- runtime-linux.md
Since #666 it's no longer guaranteed that `/proc` will exist.  And there doesn't seem to be much point in requiring symlinks which will be known broken.
This commit also tightens the timing.  Before it was just “after the container has `/proc` mounted”, which could have happened during the `delete` operation (if the container authors wanted to be especially ornery).  With this commit, I've put the creation in [step 2 of the lifecycle][1].  And within step 2, it happens after `mounts` has been processed.
[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/runtime.md#L54-L57
> runtime-linux: Condition /proc/self/fd symlinks on source existence

- runtime.md
All of these operations should be supported on all of our compliance-tested platforms.  If there are cases where a given OS cannot support one of these operations, it should be discussed in that operation's section, and the "Unless otherwise stated" qualifier makes space for that.  But leaving the reader to decide on whether a host OS supports a given operation seems too unstable for a specification.
I've also dropped the "OCI compliant" qualifier, because the (not) compliant language in `spec.md` already ties OCI compliance to the RFC 2119 language.  There's no point in mentioning "OCI compliant" outside of that section, because the "MUST" already brings in all of the compliance associations we need.
> runtime: Drop "not supported by the base OS" loophole

- runtime.md
These states are already defined in the "State" section.  There's no need to redefine them in the operation sections.
Operation-level redefinitions are dicy anyway, because they imply something testable about the immediately-after-this-operation time, and it's not possible to run race-free tests of that time (e.g. the process could die for other reasons between the successful `create` call and the `state` call you made to look for a `created` status).
> runtime: Remove status redefinitions from operations

- config.md
- runtime.md
- schema/config-schema.json
- specs-go/config.go
Since #384, it's possible for a container process to never execute user-specified code (e.g. you can call `create`, `kill`, `delete` without calling `start`).  For folks who expect to do that, there's no reason to define `process.args`.
The narrow solution to this would be to make `process.args` optional, but that approach was [rejected in favor of this all-or-nothing approach to `process` handling][1].  What an unset `process` means for the implementation-defined container process between `create` and `start` is unclear, but clarifying how that is handled is a separate issue (#700) independent of whether `process` is optional or not.
[1]: https://github.com/opencontainers/runtime-spec/pull/620#issuecomment-282820279
> config: Make process optional

- config.md
This wording just landed via #673, but the rule is generic and not unique to platform-specific properties.
Also adjust the wording somewhat to match the more established wording from the “Extensibility” section.
> config: Move valid-value rules to their own section

- runtime.md
Step 3 of the lifecycle from before this commit had two sentences which both landed in #384.  I [pushed][1] [back][2] a bit on the entry then, but we seem to be pretty comfortable with the current "keep all lifecyle entries in a one-layer enumerated list" approach, so I'm leaving that alone in this commit.  Step 3 isn't really a lifecycle step though, it's more about clarifying that you can jump around in the lifecycle instead of hitting all the steps in consecutive order.  In this commit, I've addressed that in a new paragraph that follows the list.
The other sentence from the old step 3 doesn't need replacing, because the limits are already covered in more detail in the operation sections themselves.  For example, the 'delete' operation has:
> Attempting to delete a container that does …
> runtime: Remove "features the runtime chooses to support"

- runtime.md
Based on [IRC discussion today][1]:
> @crosbymichael: just take a step back and think about it.  you have a process object in the spec.  its a single object defining what to run.  How do you run a process?  you exec its args.  From the spec pov its an atomic operation.  in between create and start its not running the users code and is left up to the runtime.  you either have a process defined by the spec and its created as an operation in the container on start or your dont.
This means that the caller has no way to set the user/cwd/capabilities/… of the runtime's container process between `create` and `start`.  You could avoid that limitation by requiring all process properties *except* `process.args` be applied at create-time, but my attempt to make `process.args` optional (which would …
> runtime: Explicitly make process.* timing implementation-defined

- Makefile
- schema/Makefile
The only `.PHONY` entry we *need* is for `schema/validate`, since that's a real file but we haven't told Make about its real dependencies (which involve complicated Go lookups).  I'm personally in favor of using `.PHONY` for all targets that aren't on-disk files, because it hints to readers that the rule is not generating a file at the target.  But there has been resistance to adding .PHONY entries to all such cases (e.g. #791), so this commit brings us around to a internally-consistent “only use `.PHONY` when you always need it” position.
That means that, for example, users who create files named `clean` will turn `clean` the target into a no-op, but runtime-spec maintainers are ok with that.
> Makefile: Remove unnecessary .PHONY entries

- bundle.md
I think this make clear what reference the directory in config.json
> bundle.md: specify root reference the directory

- config-linux.md
Catch the Markdown spec up with the JSON Schema change in #662.  The Markdown is canonical, so we could restore the explicit-null handling to the JSON Schema instead, but the [maintainers feel][1] (and I agree) that there's no point in explicitly allowing a null value when callers can simply leave the property unset.
[1]: https://github.com/opencontainers/runtime-spec/pull/555#issuecomment-272020515
> config-linux: Remove explicit 'null' from device cgroup values

- schema/test/config/good/minimal-for-start.json
- schema/test/config/good/minimal.json
It's optional since #701 which landed yesterday.
> schema/test/config/good/minimal: Drop 'process'

- config.md
fix lifecycle broken links that are left behind
> config.md: lifecycle broken links fix

- config.md
> config.md: format changes

- schema/config-schema.json
- schema/defs-linux.json
The current “[For example, valid values for Linux…][1]” wording in config.md does not seem strong enough to support this condition, especially since the spec makes no claims about what valid capabilities are for non-Linux OSes.  And `process.capabilities` has been nominally legal for non-Linux OSes since #673.
[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config.md#L135-L136
> schema/defs-linux: Drop 'Capability' type

- config.md
config.json is used for creation of container not for
operations of container, we should specify this.
> config.md: specify config usage

- config.md
Clarification that Windows does not support a read-only root filesystem.
> Windows: Clarify r/o root filesystem

- config-linux.md
> config-linux.md: fix wrong link description about cgroups

- config.md
Not sure where the mis-information came from, but the mounts section on Windows has incorrect information.
- The type is not used
- The example was incorrect as the source is not a volume path
- Better not have generic example rather than including a users name ;)
- Clarification of what the source can be (although we hope to be more reaching in future releases here)
> Windows - correct mounts

- config-linux.md
We have an [explicit policy for example header levels][1], so follow that in `config-linux.md`.  Also adjust the non-example headers to be one level deeper than their parent.
Spun off from [here][2], and we've had similar changes before in #650.  After this commit:
```
$ grep '^#' config-linux.md
```
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/style.md#anchoring
[2]: https://github.com/opencontainers/runtime-spec/pull/823#discussion_r116671574
> config-linux: Consistent header nesting

- specs-go/config.go
This should have happened in #789 as part of moving the property from a Linux-specific type to a cross-platform type.
> specs-go/config: Add a 'linux' tag to OOMScoreAdj

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
The Windows implementation of the docker daemon still passes a number of fields out of band from the OCI runtime spec. This PR addresses the `CredentialSpec` field by adding it to the runtime spec. (https://github.com/moby/moby/blob/master/libcontainerd/client_windows.go#L177-L178)
> Windows: Add CredentialSpec

- bundle.md
- config.md
- schema/config-schema.json
- specs-go/config.go
This changes the root path to OPTIONAL as it is not supported for Hyper-V containers on Windows, where the root filesystem isn't accessible on the host operating system - it only has meaning inside the utility VM running the container.
> Clarify root path

- bundle.md
- config.md
Anyone setting 'rootfs.path' should be aware of this advice, regardless of whether they're the ones composing the bundle or not.
Use the RFC 2119 “SHOULD” (vs. the old lowercase “should”) for this recommendation.  The SHOULD semantics make sense and using SHOULD avoids confusing readers (“did they mean to SHOULD this?”).
Also drop the “While the name of this directory may be arbitrary” caveat, because SHOULD already implies “but you can pick another directory name if you want”.
Note that the “MUST be present in a single directory” line which is still in `bundle.md` forbids you from picking `foo/bar`, `../foo`, or other paths that do not point at a direct child of the bundle directory.  I [don't like that direct-child restriction][1], but I'm not touching it in this commit.
[1]: …
> bundle: Move 'rootfs' recommendation to config.md

- README.md
- meeting.ics
Catch up with [this][1], effective this afternoon.  There was earlier discussion [here][2].
[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/AuNglHFyrkA
[2]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/nZ0lS4fDBbQ
> meeting.ics: Bump even-week meeting from 5pm to 2pm Pacific

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
Similar to https://github.com/opencontainers/runtime-spec/pull/814, the Windows implementation of the docker daemon still passes a number of fields out of band from the OCI runtime spec. This PR addresses the Servicing field by adding it to the runtime spec. https://github.com/moby/moby/blob/master/libcontainerd/client_windows.go#L152-L154
> Windows: Add servicing

- config.md
`list of strings` should be replaced by `array of strings`
> config.md: fix typo of context

- config-linux.md
- config-solaris.md
setup is a noun, 'set up' is a verb
> tfix: replace setup

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
Similar to #814, the Windows implementation of the docker daemon still passes a number of fields out of band from the OCI runtime spec. This PR addresses the IgnoreFlushesDuringBoot field by adding it to the runtime spec. https://github.com/moby/moby/blob/master/libcontainerd/client_windows.go#L156-L159
> Windows: Add IgnoreFlushesDuringBoot

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
Similar to #814, the Windows implementation of the docker daemon still passes a number of fields out of band from the OCI runtime spec. This PR addresses the fields required to support Hyper-V containers by adding them to the runtime spec.
> Windows: Add Hyper-V isolation fields

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
This moves the Windows network runtime options into the spec. 
NetworkResourceSettings was never used in the runtime spec, and implemented in HNS and libnetwork instead of at runtime on Windows.
/cc @RobDolinMS 
Signed-off-by: Darren Stahl <darst@microsoft.com>
> Update to Windows network options

- config-windows.md
Catching #801 up with the [anchoring policy][1].
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/style.md#anchoring
> config-windows: Fix header level for network example

- specs-go/config.go
Being a `neat freak` while going through final reviews of the spec. There were some redundant inconsistent comments in some of the Linux structures. This PR makes `config.go` consistent across all platforms in terms of the style of comment. In addition, there is no need to mention "Hyper-V containers" explicitly at the top level.  And corrected the "platform" based containers comment in the top level `Spec` structure.
> Remove redundancy in config.go

- config-windows.md
- config.md
- schema/config-windows.json
- specs-go/config.go
This relates to conversations internally here finalising and verifying the changes necessary to support Windows in the v1.0 OCI spec. Specifically the first part of this comment: https://github.com/opencontainers/runtime-spec/pull/828#issuecomment-303537717.
It turns out that between Technical Preview 5 (TP5) and RTM of Windows Server 2016, there was a platform change whereby the SandboxPath no longer needed to be passed, but was kept in for backwards compatibility as long as the layerfolderpath is populated between the runtime and HCS. I wasn't aware of this. Hence it's no longer needed in the spec. Apologies for the noise introducing it.
There are three other clarifications in this PR:
a) Clarify the root.Path for Windows Server …
> Windows: Remove Sandbox, additional tweaks

- config-windows.md
- config.md
- schema/config-windows.json
- specs-go/config.go
LayerFolders is a property that is missing from the runtime spec that is **required** for all useful containers on Windows.
[This issue](https://github.com/opencontainers/runtime-spec/issues/817) mentions extending the runtime spec with "required" platform specific fields.
> Add LayerFolders to Windows platform config

- config-solaris.md
- config.md
hey all.  i recently started working on the solaris docker port and that means i'm also responsible for the solaris components of the container runtime spec.  while looking at the spec i noticed that some of our doc links were broken.  i've never worked directly on github.com before, so i figured that fixing this would be a good way to learn the ropes and introduce myself.  so apologies in advance if i've made any noob mistakes.  cheers.
> fix docs.oracle.com links #864

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
As per https://github.com/opencontainers/runtime-spec/pull/828#discussion_r118537284, fixes https://github.com/opencontainers/runtime-spec/issues/857.
Addresses `credentialSpec`, `utilityVMPath`, and `ignoreFlushesDuringBoot`.
REMOVED ~~~I noticed there were discrepancies also, particularly in the `SolarisAnet` structure (camelCase and non-matching field names to json names), so I fixed these up at the same time.~~~
> Windows: Fix camelCase inconsistencies

- config.md
- specs-go/config.go
Made `hooks` Linux and solaris. Windows does not currently support hooks. While we might at a later date, have clarified that in the .go and .md file.
Also, as I mentioned in the description of https://github.com/opencontainers/runtime-spec/pull/854, platform-specific things are generally in the `.md` file, not the `.go` file. Hence moved the Linux comment.
> Hooks to linux,solaris and doc clarification

- README.md
- RELEASES.md
- bundle.md
- config-linux.md
- config-solaris.md
- config-windows.md
- config.md
- runtime.md
> format specs with 4 spaces indent

- config.md
This builds on #869, so review that one first.
Clarifying the language from #855 according to [this comment][0].  Without something like this commit, there's no clear way for config authors to know if their runtime will support hooks or not, and there was previous agreement that [that sort of ambiguity was not helpful][1].  This also gives normative Markdown grounding for the [Go platform tag][2] added in 28e8f68.
[0]: https://github.com/opencontainers/runtime-spec/pull/855/files#r118342685
[1]: https://github.com/opencontainers/runtime-spec/pull/472#r78088802
[2]: https://github.com/opencontainers/runtime-spec/pull/855/files#diff-7f24d60f0cbb9c433e165467e3d34838R20
> config: Require hook support on Linux and Solaris

- config.md
Not all hooks are run after creation.  In fact, there are currently no `postcreate` hooks (`prestart` hooks are called “[after the `start` operation is called but before the user-specified program command is executed][1]”.  I suggest not adding this line (and removing it from the Go comment).
There's an outside chance that folks could read the line as “after namespaces are created, not necessarily before `create` returns”, and that's correct.  But I don't think it adds anything with each hook already clearly defining when it is triggered.
Spun off from [this comment][2].
[1]: https://github.com/opencontainers/runtime-spec/blob/2ec18c02474dd49ce20aa30236959a8a80763042/config.md#prestart
[2]: https://github.com/opencontainers/runtime-spec/pull/855#discussion_r118341546
> config: Remove incorrect "after the container namespaces are created"

- config.md
This condition landed in #510 with subsequent wording tweaks in #645 and #654.  However, since #584 we forbid duplicate keys on *all* objects (not just annotations), so this PR removes the redundant annotation-specific condition.
> config: Drop redundant "unique within this map" annotation requirement

- config-linux.md
- config.md
- schema/config-linux.json
- schema/defs-linux.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
These are long enough without the prefix, and `linux.resources.blockIO.blkioWeight`, etc. are just as specific as `linux.resources.blockIO.weight`.  Generated with:
```
$ sed -i s/blkioWeight/weight/g $(git grep -l blkioWeight)
$ sed -i s/blkioLeaf/leaf/g $(git grep -l blkioLeaf)
$ sed -i s/blkioThrottle/throttle/g $(git grep -l blkioThrottle)
```
Property-name polishing inspired by #859, in case we want to clean this sort of thing up before 1.0.  If not, we can just close this PR.
> config-linux: Drop redundant 'blkio' prefix from blockIO properties

- config.md
These references had been using IEEE Std 1003.1, 2004 Edition, but:
$ curl -s http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html | grep -B2 'newer edition'
<center><font size="2">The Open Group Base Specifications Issue 6<br>
IEEE Std 1003.1, 2004 Edition<br>
Copyright &copy; 2001-2004 The IEEE and The Open Group, All Rights reserved.</font></center><center><font color="red">A newer edition of this document exists <a href="http://pubs.opengroup.org/onlinepubs/9699919799/" target="_parent">here</a></font></center>
Shifting to 2016 also syncs us with the [`file` reference][0].  The initial reasoning for the 2004 edition is unclear to me (more on that in 70858bc4).
The [change-log for the `exec` page][1] doesn't list any relevant changes, and skimming a diff of the two …
> config: Bump POSIX spec references to IEEE Std 1003.1-2008, 2016 Edition

- config.md
SHOULD [means][1]:
> … there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.
So consideration is already baked into the definition, and we can just say “SHOULD be” and warn folks whenever they use a value other than `rootfs`.
Also break this into its own paragraph, because the value recommendation is orthogonal to and less important than the value semantics covered in the preceding sentences.
[1]: https://tools.ietf.org/html/rfc2119#section-3
> config: Replace "SHOULD consider" for 'rootfs' path value

- config.md
This line landed in #673, but I'm not clear on the motivation.  The wording reads to me like “you don't have to support valid values for platform-specific fields if you don't want to”, but we already cover unsupported value handling with the [valid values section][1] separated out in #681.  This commit removes the ambiguous line.
Related issue in #813, although this commit will not close that issue.
[1]: https://github.com/opencontainers/runtime-spec/blob/837ee7659b0c115bb32598e4454a1f6d2460b1ea/config.md#valid-values
> config: Remove "MAY support any valid values" sentence

- config-linux.md
#826 added a redundant link name for libseccomp.  This commit restores the old [implicit link name shortcut][1] there and updates the other entries (all of which were for the filesystems table in config-linux) that could also use that shortcut.  This is obviously not a major change, but I think it makes the source easier to read by minimizing the markup so you can focus on the text.
[1]: https://daringfireball.net/projects/markdown/syntax#link
> config-linux: Use the implicit link name shortcut

- config.md
replace file sytem with filesystem for consistent in context
keep one sentence per line
> consistency and style fix

- config.md
Borrowing language [from `root.path`][1] for absolute/relative and [from `linux.namespaces[].path`][2] for the runtime mount namespace.
In #509 I'd [floated a generic rule for anchoring relative runtime-namespace paths][3], but there aren't all that many relative runtime-namespace paths, so this PR takes a narrower approach.
[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config.md#L33
[2]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config-linux.md#L38
[3]: https://github.com/opencontainers/runtime-spec/issues/509#issuecomment-228414738
> config: Clarify mounts[].source relative path anchor

- config.md
- specs-go/config.go
a) Tagged the `type` of mount with the correct platform tag (not applicable on `Windows`.
b) Generally, there are not platform specific comments inside the `.go` files - that why we have the `.md` files. Hence moved the `Linux` comments for mount from `config.go` to `config.md`.
c) The comment about `the path and child directories MUST exist, a runtime MUST NOT create directories automatically to a mount point.` is incorrect in the way mapped directories (which is what the runtime uses through HCS to provide "pseudo"-mounts on Windows) work. Hence made that a `Posix` comment.
> Mount correction

- glossary.md
Namespaces are not all hierarchical and processes aren't always in leaves.
Spun off from #795.
> glossary: Remove "leaf" and "hierarchy" from container namespace definition

- config.md
The old language is from #563, where nobody commented on the “if attached” wording.  But reading the old line now, it's not clear to me what `consoleSize` means when `terminal` is not `true`.
This commit explicitly declares `consoleSize` unspecified in that condition, so runtimes are free to do what they want short of erroring out.  I considered making the property undefined or requiring it to be unset, but those seemed too strict given our permissive “[MUST ignore unknown properties][1]” extensibility requirement.
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/config.md#extensibility
> config: Explicily make consoleSize unspecified if terminal is false or unset

- config-linux.md
The way that the runtime supplies these is “[truly optional][1]”, as long as they get supplied.  Also backtick `mknod`.
An uncontentious change spun off from #829.
[1]: https://tools.ietf.org/html/rfc2119#section-5
> config-linux: "may" -> "MAY" for supplying linux.devices

- config.md
> config.md: minor changes for process

- config.md
- schema/config-schema.json
- schema/test/config/good/minimal-for-start.json
- schema/test/config/good/minimal.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
Close: #725
See discussion in #830 and dev-weekly-meeting discussion
in http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2017/opencontainers.2017-06-14-21.03.log.txt
We don't use this field in runc, and mostly only
image-spec cares about this, we can assume tools know
what specific platform this spec is built for.
> Remove platform field

- bundle.md
Instead of repeating the config.md conditions, just make the linkage more clear.  Now the chain is:
1. Bundles REQUIRE a `config.json` which is a bundle artifact.
2. If that `config.json` has a `root.path` entry (as specified in `config.md`), then add the referenced directory to the set of bundle artifacts.  The `config.md` requirements include “If defined, a directory MUST exist at the path declared by the field”.
3. Apply the “MUST all be present in a single directory” condition to all bundle artifacts.  I [don't like that direct-child restriction][1], but I'm not touching it in this commit.
So these are the same requirements as before this commit, but with less redundancy and fewer words.
[1]: https://github.com/opencontainers/runtime-spec/pull/469
> bundle: DRYer root.path entry

- config-linux.md
I'd rather address runtime compliance by breaking this down into explicit checks based on POSIX stat(3) calls.  But with [that approach rejected][1], mentioning symlinks here helps motivate [runtime-tools' choice][2] of [`os.Stat`][3] (which follows symlinks) vs. [`os.Lstat`][4] (which does not).
Spun off as a non-controversial portion of the rejected #829, as requested by @crosbymichael on 2017-06-01 (although that request didn't make it [into the log][5]).
[1]: https://github.com/opencontainers/runtime-spec/pull/829#issuecomment-305582159
[2]: https://github.com/opencontainers/runtime-tools/blob/f5c82b3918bdfc3ed4b594dcfab4d1554beaf992/cmd/runtimetest/main.go#L319
[3]: https://golang.org/pkg/os/#Stat
[4]: https://golang.org/pkg/os/#Lstat
[5]: …
> config-linux: Explicitly allow symlinks for providing devices

- config.md
hcsshim supports [readonly](https://github.com/Microsoft/hcsshim/blob/master/interface.go#L31) option.
Signed-off-by: Amin Jamali <ajamali@pivotal.io>
> Add readonly option for mount

- runtime.md
> Allow created containers to be killed

- config-linux.md
- config.md
- schema/config-linux.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
The kernel ABI to these values is a string, which accepts the value `-1`
to mean "unlimited" or an integer up to 2^63 for an amount of memory in
bytes.
While the internal representation in the kernel is unsigned, this is not
exposed in any ABI directly. Because of the user-kernel memory split, values
over 2^63 are not really useful; indeed that much memory is not supported,
as physical memory is limited to 52 bits in the forthcoming switch to five
level page tables. So it is much more natural to support the value `-1` for
unlimited, especially as the actual number needed to represent the maximum
has varied in different kernel versions, and across 32 and 64 bit architectures,
so determining the value to use is not possible, so it is necessary to write
the string `-1` to the cgroup files. …
> Make Linux memory allocations int64 not uint64

- config-linux.md
> config-linux.md: add cgroupsPath entry and some modifications

- config.md
- schema/config-schema.json
- specs-go/config.go
Don't require users targetting Hyper-V to set an empty object (`"root": {}`).  This also avoids confusion about whether you can set `root.readonly` without setting `root.path` (you can't).
Following #820.
> config: Bump Hyper-V condition from root.path to root itself

- schema/README.md
Despite this not being a valid link, until this spec has its v1.0.0
release, this URL ought to be accurate for once the this spec is tagged
v1.0.0
Part of #726 
> *: update link to v1.0.0

- config.md
- specs-go/config.go
This rebased  @wking's #835 changes, and added a clarification on POSIX-specific properties such as rlimits.
> rebase: config: Make capabilities, noNewPrivileges, and rlimits Linux-only (again) 

- ChangeLog
- specs-go/version.go
The vote for this version: https://groups.google.com/a/opencontainers.org/d/msg/dev/3wLazzsd4GI/2vi0gsxtAwAJ
Since the [rc5 release](https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5) there have 128 changesets merged:
#880
#881
#838
#877
#823
#876
#875
#868
#873
#840
#850
#809
#874
#871
#863
#852
#854
#735
#811
#827
#851
#847
#858
#860
#862
#870
#846
#855
#859
#865
#828
#849
#856
#837
#848
#801
#818
#816
#822
#807
#815
#833
#839
#820
#814
#836
#832
#821
#824
#826
#819
#803
#766
#724
#812
#805
#804
#798
#802
#700
#732
#681
#701
#702
#733
#736
#767
#790
#799
#800
#713
#796
#703
#793
#789
#730
#794
#737
#792
#756
#764
#781
#785
#786
#787
#784
#783
#788
#777
#775
#768
#769
#773
#778
#780
#770
#776
#774
#761
#765
#763
#750
#758
#757
#739
#748
#753
#751
#749
#752
#740
#744 …
> bump to v1.0.0-rc6

- schema/defs-linux.json
According to https://github.com/opencontainers/runtime-spec/blame/master/config-linux.md#L544.
> defs-linux: add action to to syscalls required

- ChangeLog
Through f4d221c (Merge pull request #880).  The rc6 release picked up an earlier version of these notes in b94a1ec, and those entries are mostly unchanged except for:
* The `credentialSpec` entry, which was #814 for `credentialspec` and now also includes #859 for `credentialSpec`.
* The `root(.path)` Hyper-V entry, which was #820 for `root.path` and now also includes #838 for `root`.  I also moved this into the “breaking changes” section, because rc5 Hyper-V configs required `root` to be set, and rc6 Hyper-V configs require it to not be set.  Although whether rc5 allowed Hyper-V configs at all is not clear to me.
* Fixed indenting for the typo-fixes entry, as well as a number of more recent typo-fix PRs.
There are also a number of completely new entries to cover the remaining changes …
> ChangeLog: Document changes since c83b8c8

- config-linux.md
- config.md
- schema/config-linux.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
> config-linux: Move 'disableOOMKiller' under 'memory'

- runtime.md
- schema/state-schema.json
- specs-go/state.go
> Make pid option on platforms other than linux

- ChangeLog
- specs-go/version.go
Vote for this release: https://groups.google.com/a/opencontainers.org/d/msg/dev/_pvFMQN1DUM/YoEdnfXGBQAJ
No changes sense rc6 tag
> Release v1.0.0

- config-linux.md
There is no procfs type in Linux, it will confuse readers.
> modify procfs to proc

- config.md
Catching up with #905, because it's strange to change one link label from `procfs` → `proc` but leave the other.  This will also make it marginally easier to collapse these to a single link label once we [convert the spec to a single Markdown file][1].
[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/1Wwd_MEzSjI/DsCkR-UwAgAJ
> config: Fix “procfs_2” → “proc_2” link label

- config-windows.md
https://github.com/opencontainers/runtime-spec/blame/master/specs-go/config.go#L459
https://github.com/opencontainers/runtime-spec/blame/master/schema/config-windows.json#L43
> config-windows: fix the type of maximum

- schema/config-schema.json
> config-schema: Optimize code

- runtime.md
The latter is much more common:
```
$ git --no-pager grep -ic "process in the container" origin/master -- *.md
origin/master:runtime.md:1
$ git --no-pager grep -ic "container process" origin/master -- *.md
origin/master:config-linux.md:4
origin/master:config.md:2
origin/master:glossary.md:1
origin/master:runtime.md:5
```
Spun off from [here][1].
This seems like a patch-level change to me, so folks may want to put it in the [v1.0.Z milestone][2].
[1]: http://ircbot.wl.linuxfoundation.org/eavesdrop/%23opencontainers/%23opencontainers.2017-08-03.log.html#t2017-08-03T21:27:57
[2]: https://github.com/opencontainers/runtime-spec/milestone/16
> runtime: Change "process in the container" -> "container process"

- config.md
The capitalization in “Container Configuration file” (which we've used since #176) was halfway between “Title Case” and “Sentence case”.  The current spec isn't particularly consistent (e.g. we have both “Specification version” and “POSIX-platform Mounts”), but the ToC has used “Configuration” for this file since #626, so dodge the sentence/title issue and use that here too.
> config: Simplify title to "Configuration"

- config-linux.md
blkioWeightDevice is not direct for bindwidth rate limit, actually
used for weight division.
bpsdeivce limits are different from IOpsdevice, they are limit
rate in bytes, say used for bandwidth limit will be better.
> config-linux.md: part fix of blkio spec

- config.md
- schema/config-schema.json
- schema/defs.json
- spec.md
- specs-go/config.go
Consistently reference ourselves.  Adding “Initiative” catches us up with #571, and expanding OCI is more consistent with the rest of the spec:
$ git --no-pager grep --count 'Open Container Initiative Runtime Specification'
README.md:1
config.md:2
schema/config-schema.json:1
schema/defs.json:2
spec.md:1
specs-go/config.go:1
$ git --no-pager grep --count 'OCI Runtime Specification'
spec.md:1
> *: Add "Initiative" to OCI Runtime Specification and expand OCI

- .pullapprove.yml
Pull in changes from opencontainers/project-template#29.  The only changes vs. the upstream version is removing all the groups except for the `runtime-spec` group.
> .pullapprove.yml: Switch to v2 and other project-template updates

- README.md
- meeting.ics
On @caniszczyk's [recommendation][1], make the meetings 5pm Pacific on the first Wednesday of each month.
I've also removed the requirement for posting minutes to the mailing list.  We have a good track record of pushing MeetBot minutes to the same place, so I don't think we add any usefulness by mailing that link to the list.  I'm happy to split that off into a separate PR if there's any pushback on it.
[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/PC2DzxarMqA/SVF0KiY3AgAJ
> README: Make meetings monthly (were weekly)

- config.md
Fixing a typo I'd made in 5292e9c8 (#880).
I think this is a patch-level change, so it can be tagged [v1.0.Z][1] (although we have had a few patch-level PRs merged without adding them to that milestone).
[1]: https://github.com/opencontainers/runtime-spec/milestone/16
> config: Add a trailing period to the "cannot be mapped" rlimits line

- implementations.md
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
> Add new "cc-runtime" to list of implementations.

- .mailmap
Preferring his new (more detailed) name:
$ git log --decorate --author james.o.hunt | grep -B1 Author
commit e27acdd9ca0a6218ec77cca99eceb785696d9405 (origin/pr/922)
Author: James O. D. Hunt <james.o.hunt@intel.com>
--
commit 30bc03316827834bafb03409fab49576b3beb530 (origin/pr/539)
Author: James Hunt <james.o.hunt@intel.com>
CC @jodh-intel.
> .mailmap: Consolidate James' entries

- config.md
> Fix link on IEEE Std 1003.1-2008

- config-linux.md
The old language is from 72cbff67 (#720), but without RFC 2119 language in the absolute path wording, it's not a compliance requirement (per [`spec.md`'s “compliant” definition][1]).  This commit adjusts the language to bring it in line with our current wording for [`maskedPaths`][2] and [`readonlyPaths`][3], which we've had since 25f44dd0 (#587).
This is technically a breaking change, because a config with a relative namespace path would have been compliant before, but will be non compliant with this PR.  However, I think the previous “an absolute path to namespace file” wording is clear enough that config authors are unlikely to be relying on relative namespace paths in configs.  If we are comfortable enough with that assumption (I am, but I'm not a maintainer), we can push this out as …
> config-linux: RFC 2119 MUST for absolute linux.namespaces[].path

- ChangeLog
- specs-go/version.go
Since 1.0.0:
4ebb31efe97cf3daedb1e331663395edfb56f284 Merge pull request #925 from wking/absolute-namespace-path-must
34170989dc28be797f7078f88df156a474d7fd11 Merge pull request #913 from rutsky/fix-link
a8125598b32a65ff55c83214d3c262383178e7fa Merge pull request #924 from wking/mailmap
f09dac8ed963f3a77561f45372de940f823ef351 Merge pull request #922 from jodh-intel/implementations-add-cc-runtime
325e66a6635c2bc78fafbfd994010c9ea4ead824 Merge pull request #921 from giuseppe/fix-typo
689521f Merge pull request #915 from wking/rlimits-unmapped-period
f5f1390 Merge pull request #910 from wking/monthly-meetings
ec96974 Merge pull request #902 from wking/pull-approve-v2
2a67f81 Merge pull request #900 from wking/oci-runtime-specification
3294695 Merge pull request #825 from …
> Release 1.0.1

- config.md
I'd broken this in 2022e3ec (#838), where I'd misread the initial bolding `**` as a list bullet or something :/.  The extra indents don't cause a problem for the first paragraph, but they [cause the “On all other platforms…” paragraph to be interpreted as a `<pre>` block][1].
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.1/config.md#root
> config: Dedent root paragraphs, since they aren't a list entry

- README.md
- runtime.md
> fix the link to hook

- schema/config-linux.json
- schema/config-schema.json
- schema/config-solaris.json
- schema/config-windows.json
- schema/state-schema.json
We're using [JSON Schema draft-04][1], as [declared][1.5] by our [`$schema` properties][2].  In draft-04, the `id` keyword alters the resolution scope.  But our current `$ref` values use [JSON Pointers][4] with relative references like `defs-linux.json#/definitions/Device` that ignore the `id`s.
By draft-07, `id` has become `$id`, and [the docs say][5]:
> The root schema of a JSON Schema document SHOULD contain an "$id" keyword with a URI (containing a scheme).
But since xeipuuv/gojsonschema@83a7f6369d5, including any URI that cannot be retrieved generates an error:
```console
$ ./validate config-schema.json test/config/good/minimal.json
Could not read schema from HTTP, response status is 404 Not Found
```
While a root `id` entry would be nice, we don't currently host these anywhere with …
> schema: Completely drop our JSON Schema 'id' properties

- schema/Makefile
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
> schema/Makefile: fix test

- config-linux.md
- schema/config-linux.json
- schema/defs-linux.json
- schema/test/config/bad/linux-rdma.json
- schema/test/config/good/linux-rdma.json
- specs-go/config.go
This request is for the inclusion of RDMA controller/cgroup which is added in Linux kernel 4.11.
Background:
RDMA Networking adapters provide low latency, direct access to hardware (HCA) to user space applications to send/receive messages and data in a clustered systems.
With latest HCAs, application to application level messages delivery latency can be as low as < 1usec.
RDMA kernel subsystem achieves this using RDMA resources such as QPs, MRs CQs objects.
RDMA cgroup allows limiting resources of the such RDMA HCA networking adapters.
RDMA resource creations such as hca_handle and hca_objects must be controlled so that certain set of processes doesn't take away all hardware resources.
RDMA controller allows limiting such HCA resource on per HCA basis.
Example implementation of this …
> Add definitions for RDMA controller/cgroup of Linux kernel 4.11

- config-linux.md
- config.md
- schema/defs.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
"man 7 user_namespaces" explains the format of uid_map and gid_map:
```
<containerID> <hostID> <mapSize>
```
The order of map entries in JSON does not matter. But for the clarity of
the spec, I find it easier to understand if the order of the JSON fields is
the same as the order of the fields in the underlying uid_map/gid_map
files.
I am about to file a PR in runtime-tools because the fields in
uid_map/gid_map were parsed in the wrong order.
Signed-off-by: Alban Crequy <alban@kinvolk.io>
> uidMappings: change order of fields for clarity

- config-vm.md
- config.md
- schema/config-schema.json
- schema/config-vm.json
- schema/defs-vm.json
- spec.md
- specs-go/config.go
This adds a section to describe VM based container configurations to be
used by OCI runtimes using hardware virtualization to provide another
layer of isolation.
As part of this section we define 3 entries:
-  A virtual machine root image opbject. This is the guest image that
contains the virtual machine root filesystem. The container image will
be mounted on top of that filesystem.
- A virtual machine kernel object. This is the kernel that will boot
inside the virtual machine. The object describes the host kernel image
path, additional parameters and an optional guest initrd for the
kernel to use.
- A virtual machine hypervisor object. This is the hypervisor that will
manage the container virtual machine from the host. The object
describe a hypervisor binary path and some additional …
> config: Add VM-based container configuration section

- config.md
The links pointing to independent and specific filesystems options doesn't work
> config: Fix Linux mount options links

- config.md
The spec didn't say whether the hooks are executed in the container
environment or not (in Linux namespaces, with cgroups and rlimits
applied).
In rkt, hooks are executed in the container environment. In runc, hooks
are executed outside of the container environment.
The example with setting up the network namespace in "prestart" suggests
that the command is generic and does not have to exist in the container
rootfs. So I assume the spec was meant to say hooks are executed outside
of the container environment.
Signed-off-by: Alban Crequy <alban@kinvolk.io>
> config: Clarify execution environment for hooks

- .travis.yml
- Makefile
[Go 1.10 was released on 2018-02-16][1] and [Go only supports the last two major releases][2] (so currently 1.9 and 1.10).  Besides ensuring that we are compatible with the currently-maintained releases, this will avoid our current test failure now that [golint has dropped support for Go 1.6][3]:
```console
$ make install.tools
go get -u github.com/golang/lint/golint
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:77: undefined: io.SeekCurrent
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:80: undefined: io.SeekCurrent
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:156: undefined: io.SeekCurrent
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:187: r.declReader.Reset undefined (type bytes.Reader has no field or method Reset) …
```
> .travis: Bump minimum Go version to 1.9

- implementations.md
We should also add gvisor to the list, although not sure where to put it.
https://github.com/google/gvisor
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Add gVisor to the implementations list

- config-linux.md
The man page we linked was [removed][1] without replacement [in man-pages-4.06][2].  We can just drop our link here, because the remainder of the sentence provides enough information to calculate [the device's type and major/minor][3].
While I'm touching this line, I've added some missing backticks around path and property literals, and I've made the `terminal` reference a link.
[1]: https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/commit/?id=0f9e6478e403b26c24ecaa6761bc53d05cf04265
[2]: https://bugzilla.kernel.org/show_bug.cgi?id=110481
[3]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/devices.txt?h=v4.16#n2080
> config-linux: Drop console(4) reference

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
Signed-off-by: Dinesh Govindasamy <dingov@microsoft.com>
Co-Authored-By: msabansal <sabansal@microsoft.com>
> Support for network namespace in windows

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
Previously, it will create a dedicated RDT Class of Service (CLOS) for each running container, even they have exactly same Scheam. This will lead to short of CLOS, since there is a hardware limit for the number of CLOS, around 16 CLOS per platform.
This PR add one parameter 'closID' into existed spec to allow user to specify which RDT Class of Service (CLOS) the container will be located. So it can place these containers with same Schema into one single CLOS.
Example:
```
"linux": {
"intelRdt": {
"closID": "guaranteed_group",
"l3CacheSchema": "L3:0=ffff0;1=3ff"
}
}
```
Fixes: [runc issue 1878](https://github.com/opencontainers/runc/issues/1878)
> config-linux: add Intel RDT CLOS name sharing support

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
Add support for Intel Resource Director Technology (RDT) /
Memory Bandwidth Allocation (MBA). Add memory bandwidth resource
constraints in Linux-specific configuration.
In this PR, the spec for memory bandwidth (memBwSchema) keeps
the same format as existed spec for L3 cache (l3CacheSchema)
for consistency and compatibility in runtime-spec 1.x.
Example:
```
"linux": {
"intelRdt": {
"l3CacheSchema": "L3:0=7f0;1=1f",
"memBwSchema": "MB:0=20;1=70"
}
}
```
This is the prerequisite of this runc proposal:
https://github.com/opencontainers/runc/issues/1596
For more information about Intel RDT/MBA, please refer to:
https://github.com/opencontainers/runc/issues/1596
Signed-off-by: Xiaochen Shen <xiaochen.shen@intel.com>
> config-linux: add Intel RDT/MBA Linux support

- config.md
- The 'source' of a bind mount can either be a file or a directory.
- The 'type' field is a dummy  in case of bind mounts, often left to
"none" (in that case it does not have to be something listed in
/proc/filesystems).
- 'Relative' paths can only be used for bind mounts, not for other
mounts. That's how runc manages this.
Replaces: https://github.com/opencontainers/runtime-spec/pull/967
Signed-off-by: Alban Crequy <alban@kinvolk.io>
> config: clarify source mount

- config-linux.md
- specs-go/config.go
This is the prerequisite of runc PR:
https://github.com/opencontainers/runc/pull/1919
MBA Software Controller feature is introduced in Linux kernel v4.18.
It is a software enhancement to mitigate some limitations in MBA which
describes in kernel documentation. It also makes the interface more user
friendly - we could specify memory bandwidth in "MBps" (Mega Bytes per
second) as well as in "percentages".
We could enable this feature through mount option "-o mba_MBps":
mount -t resctrl resctrl -o mba_MBps /sys/fs/resctrl
In runtime-spec, we handle both memory bandwidth schemata in unified
format: "MB:<cache_id0>=bandwidth0;<cache_id1>=bandwidth1;..."
The unit of memory bandwidth is specified in "percentages" by default,
and in "MBps" if MBA Software Controller is enabled.
For more …
> config-linux: documentation change for Intel RDT/MBA Software Controller support

- config.md
- schema/config-schema.json
- specs-go/config.go
Windows natively doesn't launch processes through an array of arguments. Instead, it uses a command line single string, which the startup code (eg https://docs.microsoft.com/en-us/previous-versions/ms880421(v=msdn.10)) interprets into an argv set. Golang does identical parsing of the command-line on Windows in commandLineToArgv: https://github.com/golang/go/blob/ff7b245a31394b700a252fd547cf16ad0ad838b6/src/os/exec_windows.go#L100-L174
See the MSDN `CreateProcess` documentation for the actual API into Windows: https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa
Using args alone on Windows has possible loss of fidelity causing some commands to not operate as expected. (This has long …
> Windows:Have native CommandLine in Process

- README.md
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
This will update the code-of-conduct.md document to point to the one (that will be linked) from the updated org repo. The current points to the "tob" repository.
> updating link to code of conduct in org repository

- config-linux.md
If container b joins container a's pid namespace, processes inside container b can be able to see other processes in container a, not only inside it's own container..
For example:
Use busybox image as rootfs, with start arg ["sleep", "100000"]:
For `container a`: use new pid namesapce without path: `"namespaces": [{"type": "pid"}`
```
root@demo:/opt/busybox# ../runc/runc run -d a
root@demo:/opt/busybox# ../runc/runc list
ID          PID         STATUS      BUNDLE                                            CREATED                          OWNER
a           3162        running     /opt/busybox   2019-04-08T11:34:02.449638033Z   root
root@demo:/opt/busybox# ../runc/runc exec -t a ps -ef
PID   USER     TIME  COMMAND
1 root      0:00 sleep 100000
6 root      0:00 ps -ef
```
For `container b`: …
> change new pid namespace description

- specs-go/config.go
LinuxNamespaceType is defined but it is only used for PIDNamespace.
I think all Namespaces should use this type.
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
> Fix Namespaces to use LinuxNamespaceType

- config.md
Correct ociVersion is not specified in Configuration Schema Example.
ociVersion 0.5.0-dev does not support Linux ambient capability.
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
> Fix ociVersion of Configuration Schema Example to support ambient capability

- config-linux.md
- config.md
- schema/config-linux.json
- schema/test/config/bad/linux-hugepage.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
Currently the docs don't say anything about what the "pageSize" is other
than the fact that it is a string. This makes it easier for developers
to understand how it works, and may help avoiding mistakes which are
hard to spot.
This can help other doing the same mistake as `runc` and k8s when using hugepages, used `<size>kB` instead of the correct `<size>KB`. (https://github.com/opencontainers/runc/pull/2065)
Signed-off-by: Odin Ugedal <odin@ugedal.com>
> config-linux: add more info about hugetlb page size

- config-linux.md
This fixes some escaping for the `<` and `>` characters in markdown:
master:
With this PR:
> Fix markdown escape in config-linux

- README.md
We should keep the OCI contributor/maintainer dev meeting information in
the new "org" repo and all other repos should point there. This
minimizes places we need to update in the future if our meeting
technology or meeting frequency changes again.
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>
> Update meeting info section to point to "org" repo

- implementations.md
crun was moved from github.com/giuseppe/crun to
github.com/containers/crun.
> implementations.md: fix repository for crun

- config-linux.md
- schema/config-linux.json
- schema/defs-linux.json
- specs-go/config.go
allow to specify what flags must be passed to seccomp(2) when
installing the filter.
> config-linux: support seccomp flags

- config-linux.md
- schema/defs-linux.json
- specs-go/config.go
Updating documentation with a new seccomp action made available on libseccomp v2.4.0.
PR to implement this on runC:
https://github.com/opencontainers/runc/pull/1951
Libseccomp release:
https://github.com/seccomp/libseccomp/releases/tag/v2.4.0
Signed-off-by: Paulo Gomes <paulo.gomes.uk@gmail.com>
> Add new seccomp action

- config.md
- schema/config-schema.json
- schema/defs.json
- specs-go/config.go
Users may want to specify the umask(2) of the init process in a
container. This value is identical in semantics to POSIX. This is in
order to allow usage of an OCI container for a service which normally
only inherits the umask given to it.
See-also: https://github.com/opencontainers/runc/issues/1650
Requested-by: @leberknecht
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> config: add "umask" field to POSIX "user" section

- config-linux.md
- schema/config-linux.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
Addresses issue https://github.com/opencontainers/runtime-spec/issues/984
Signed-off-by: Tom Godkin <thgodkin@gmail.com>
Co-authored-by: Claudia Beresford <cberesford@pivotal.io>
> config-linux: Add Memory cgroup's use_hierarchy

- config-linux.md
- specs-go/config.go
A lot of people use the Linux `personality` support to allow a 64 bit machine
to emulate a 32 bit machine. In particular if you just run 32 bit binaries, many
build processes will fail as `uname` will still return a value appropriate for
a 64 bit system. Including the personality syscall wil change this to reflect the
value from a 32 bit system, such as `i686` rather than `x86_64`.
Note that this patch only supports the base 32 bit/64 bit calls. The other options
are largely obsolete and rarely used. I left flexibility to add other base domains
and to add flags in future, but I am not sure there is any demand for them. The
only use case I found in the recent past was the `ADDR_NO_RANDOMIZE` option that
disables ASLR, which older versions of Emacs required, but generally they set this …
> Add Linux personality support

- config.md
Generating an error seems like one potential violation of the requirement to ignore unknown properties.  Compliance testing for the ignore requirement can cite the MUST I've written here for any noticeable runtime activity around the unknown property without needing a error-specific MUST.
We've had the two MUSTs since #510, citing opencontainers/image-spec#164.  [I'd][2] [asked][3] for consolidated phrasing then, but hadn't followed up after the commit landed.
I've left a line mentioning the error activity as non-normative clarification, but am also happy to drop that line completely.
Also:
* Update the unknown annotation entry to reference the generic extensibility section, because there's nothing annotation-specific in how we want runtimes to handle unknown keys.
* Remove “reading or …
> config: Collapse extensibility to a single MUST

- runtime.md
The old wording was ambiguous.  For example, if the configuration had ociVersion set to 1.0.0 and the container was created with a 1.1.0 runtime, which version should show up in the state?
With this commit, we use the version which matches the state schema, because the config/runtime versions used for creation don't seem particularly important once the container has been created, while the state schema version is important for state consumers.  For example, if new properties were added to the state spec between 1.0.0 and 1.1.0, a consumer would want to see 1.1.0 in the state's ociVersion so it could decide whether it could rely on those new properties.
> runtime: Clarify ociVersion as based on the state schema

- schema/defs-linux.json
Signed-off-by: 0x0916 <w@laoqinren.net>
> schema/defs-linux: change weight type to uint16

- config.md
- runtime.md
- schema/config-schema.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
Hello!
Since we discussed this during the last OCI weekly meeting, I wanted to continue the conversation on a more concrete change.
Related:
- https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/WTHcf-b3wXA
- https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/_dmqMkvX_iE
I've used the same names as LXC for the hooks. I'm happy to change them if we feel there are more appropriate names.
My reasoning while drafting this was to answer some of these questions:
- Definition: How can we define the `mount` hook in a way that would clearly define the ability to mount "stuff" inside the container
- Ordering: Is there an ordering that is required?
Here it would be helpful to define the ordering such that the pre-start hook detects that it doesn't need to be executed in a …
> Add create-host, create-container, start-container hooks

- RELEASES.md
It's been a couple of years and I have no idea what I am doing.
Some of this could be automated, but for now I've included some of the
shell that gets close to the process.
> RELEASE: document how to do the release

- RELEASES.md
- config-linux.md
- config-solaris.md
- config-windows.md
- config.md
@vbatts [asked](https://github.com/opencontainers/runtime-spec/issues/1010#issuecomment-582040551) if I could rebase #937 by @Mashimiao, which I did here.
There were some trivial conflicts in `config.md`, `config-linux.md` & `config-windows.md`. The only question was whether to add asterisks around `l3cacheSchema`, compare the original [here](https://github.com/opencontainers/runtime-spec/pull/937/files#r375104291). I went and added them here as well, but those can easily be removed.
> Rebase #937

- .pullapprove.yml
- Makefile
> PullApprove: No need for 3 DCO checks

- config-linux.md
I [offered](https://github.com/opencontainers/runtime-spec/pull/975#issuecomment-594445440) to rebase #975 by @dongsupark, which had grown conflicts with master and wasn't getting much attention anymore, so here it is.
Fixes #973 
Closes #975
Edit: following review, does not include the portion about `shared+slave` from #975.
> config-linux: describe more about rootfs mount propagation (cont'd)

- config-linux.md
System administrators can pre-configure set of closIDs that can
be assigned to containers. If closID is specified and present,
runtime can just assign container to it.
> Clarify case with pre-configured Intel RDT closID

- config-linux.md
- schema/defs-linux.json
- specs-go/config.go
some seccomp actions allow to specify the errno code returned for the
syscall.
Add a new attribute to the seccomp syscall so the default EPERM can be
overriden.
> seccomp: allow to override errno return code

- specs-go/config.go
commit 3bfcde28eab5d7e107ddd3771fc92399332932a8 introduced errnoRet
for seccomp syscalls but the Go specs were not implemented correctly.
> seccomp: fix go-specs for errnoRet

- runtime.md
Hello!
As a followup of the OCI Weekly Discussion on 5/20/2020, as well as discussions on the runc [hooks Pull Request](https://github.com/opencontainers/runc/pull/2229#discussion_r426957106), I've updated the definition of the PID field for the state structure.
We are updating it with the following definition in mind:
- Runtime namespace hooks get runtime/absolute information
- Container Namespace hooks get container/relative information
/cc @cyphar @mrunalp @mikebrow 
Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>
> Define State for container and runtime namespace

- config-linux.md
- schema/defs-linux.json
- specs-go/config.go
Adds support for SCMP_ACT_KILL_PROCESS, which allows users to kill the entire process when a syscall blocked by seccomp is called.
Signed-off-by: Paulo Gomes <pjbgf@linux.com>
> seccomp: Add support for SCMP_ACT_KILL_PROCESS

- specs-go/state.go
Hello!
The [State definition ](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#state) defines 4 constants for the status field that are not present in the specs-go
This PR adds them to the state.go file to make it available to runc.
/cc @cyphar @mrunalp @mikebrow
Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>
> Add State status constants to spec-go

- specs-go/config.go
otherwise it is not possible to know whether it was specified or it is
set to 0.
> config.go: make umask a pointer

- specs-go/state.go
Following up on @kolyshkin 's [comment](https://github.com/opencontainers/runtime-spec/pull/1046#discussion_r457674394), we realized I should have updated the `State` structure to use that new type.
Thanks for picking up on this mistake!
/cc @kolyshkin @titanous 
Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>
> Update State structure to use the new ContainerState type

- implementations.md
Added the Inclavare Containers project runtime to the list of implementations.
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>
> docs: Added enclave OCI runtime rune to implementations

- config-linux.md
- config.md
- specs-go/config.go
We want to move to more enclusive names/terms in our code, and remove problematic language
from code and comments.
We want to change reference for whitelist/blacklist to allowlist/denylist.
https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
> Change all references from whitelist to allowlist

- schema/defs.json
Fixes #1051, making the schema definition for 'int64' and 'uint64' types have the expected ranges:
* `int64` minimum is -2^63
* `int64` maximum is 2^63-1
* `uint64` maximum is 2^64-1
Signed-off-by: John Bartholomew <jpa.bartholomew@gmail.com>
> Fix int64 and uint64 type value ranges

- config-linux.md
- schema/defs-linux.json
- specs-go/config.go
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
> Update seccomp architectures to support RISCV64

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
allow users to specify cgroup v2 resources.
Each element in the map refers to a file in the cgroup v2 hierarchy and the element value has its content.
> cgroup: add cgroup v2 support

- .travis.yml
Without this, Travis CI only works on the main repository (github.com/opencontainers/runtime-spec) but not on forks. It is useful
to make Travis CI work on forks for contributors to be able to test their work before submitting a PR upstream.
See:
https://docs.travis-ci.com/user/languages/go#go-import-path
Symptoms:
```
$ make docs
go run ./.tool/version-doc.go > version.md
.tool/version-doc.go:10:2: cannot find package "github.com/opencontainers/runtime-spec/specs-go" in any of:
/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/github.com/opencontainers/runtime-spec/specs-go (from $GOROOT)
/home/travis/gopath/src/github.com/opencontainers/runtime-spec/specs-go (from $GOPATH)
Makefile:53: recipe for target 'version.md' failed
make: *** [version.md] Error 1
The command "make docs" …
```
> travis: fix go_import_path

- config-linux.md
- schema/defs-linux.json
- specs-go/config.go
The seccomp action has been added to libseccomp a while ago, so I guess
the runtime spec should support it as well:
https://github.com/seccomp/libseccomp/commit/b2f15f3d02f302b12b9d1a37d83521e6f9e08841
> Add support for SCMP_ACT_KILL_THREAD

- Makefile
Otherwise, commands like "make install.tools" fail with:
$ make install.tools
go get -u github.com/golang/lint/golint
code in directory /<path>/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
The github repository says this URL should be used for go get. After
this patch, make install.tools works just fine.
Signed-off-by: Rodrigo Campos <rodrigo@kinvolk.io>
> Makefile: Fix golint URL used in go get

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
the specs already support overriding the errno code for the syscalls
but the default value is hardcoded to EPERM.
Add a new attribute to override the default value.
> seccomp: allow to override default errno return code

- config-linux.md
- schema/config-linux.json
- schema/defs-linux.json
- specs-go/config.go
- specs-go/state.go
Hi!
This is a follow-up of PR #1073 using the alternative [discussed here](https://github.com/opencontainers/runtime-spec/pull/1073#issuecomment-719465555). The reasoning to go this way over the others [is here](https://github.com/opencontainers/runtime-spec/pull/1073#issuecomment-720524314)
I’m a co-worker of @alban and the commit has his sign-off too :)
This adds the specification for Seccomp Userspace Notification and the
Golang bindings. This contains:
- New fields in the seccomp section to use with seccomp userspace
notification.
- Additional SeccompState struct containing the container state and file
descriptors passed for seccomp.
This was discussed in the OCI Weekly Discussion on September 16th,
2020. After review on github, this implementation was changed to the
"Proposal with …
> Add Seccomp Notify support using UNIX sockets and container metadata

- schema/defs-linux.json
- specs-go/config.go
In PR https://github.com/opencontainers/runtime-spec/pull/1074 I missed some consts, sorry!
Funny thing is we didn't catch them even when we used this in runc and containerd patches because containerd just passes a string (see commit for a detailed explanation) and runc doesn't use these constants (again, full explanation in the commit msg).
cc @vbatts @giuseppe as you LGTM to #1074.
> Fix seccomp notify inconsistencies

- config.md
(probably) supersedes https://github.com/opencontainers/runtime-spec/issues/1071 "Proposal: define a "ALL_CAPS" pseudo-capability to grant all capabilities"
Relates to:
- https://github.com/moby/moby/issues/41562 / https://github.com/moby/moby/pull/41563 "Unknown capability "CAP_PERFMON" on Linux 5.8.14"
- https://github.com/containerd/containerd/pull/5017 oci.WithPrivileged: set the current caps, not the known caps
- https://github.com/kubernetes-sigs/kind/issues/2058 kube-proxy doesn't start up due to "apply caps: operation not permitted" error
- https://github.com/cri-o/cri-o/issues/4478 Privileged Containers do not Start: "unknown capability: CAP_PERFMON"
- https://github.com/kubernetes/kubernetes/pull/92863 kubelet & kube-proxy: ignore sysctl errors and rlimit errors when running in …
> Proposal: runtime should WARN / ignore capabilities that cannot be granted

- config-linux.md
- An attempt to make the spec easier to interpret by grouping all ClosID related contraints in one place.
- fix indentation on IntelRdt, and split out the rules regarding interdependency of parameters into a separate list.
> config-linux: clarify the handling of ClosID RDT parameter

- config-zos.md
- config.md
- schema/config-schema.json
- schema/config-zos.json
- schema/defs-zos.json
- schema/test/config/good/zos-minimal.json
- spec.md
- specs-go/config.go
As discussed in the 1/27/2021 OCI developer meeting, these changes introduce IBM z/OS as a Native Platform for OCI. Changes to code, JSON schema, and markdown documentation is included.
Other than `zos` being added a _platform_ and having its own platform-specific configuration, nothing new is really added with this. The expectation is that additional pull requests (preceded by development discussions, if needed) will be used to request any z/OS-unique configuration properties as the IBM initiative to support OCI containers on z/OS progresses.
*Note on z/OS devices:* it is the only property in the z/OS-specific configuration object. This was copied from how devices can be specified for Linux. Specifying devices like this would be a perfectly valid way to define/create devices in a …
> Introduce zos as platform

- schema/defs-zos.json
Hi Team, 
Following PR makes sure that `des-zos.json` is consistent with schema definition w.r.t to entire spec.  
I think following PR ( https://github.com/opencontainers/runtime-spec/pull/1095 )  has introduced type-resolution issues on downstream parsers. 
Specifying definition-files for types present in existing `.json` would result in infinite type resolution loop. However existing convention is just using `#` instead of specifying def-file for example  https://github.com/opencontainers/runtime-spec/blob/master/schema/defs-linux.json
Thanks
> defs-zos: [Fix] prevent schema parsers from hitting recursion-loop while resolving types.

- runtime.md
In PR #1008 three new steps in the lifecycle were added(4./5./7.) and the referencing of the states to the corresponding lifecycle step was not adjusted. Based on Tag v1.0.0-rc6, the references to the lifecycle steps were corrected.
> fix the lifecycle reference in the states listing

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
Add support for Intel Resource Director Technology (RDT) /
Cache Monitoring Technology (CMT) and Memory Bandwidth Monitoring (MBM).
Example:
```
"linux": {
"intelRdt": {
"enableCMT": true,
"enableMBM": true
}
}
```
This is the prerequisite of this runc proposal:
https://github.com/opencontainers/runc/issues/2519
For more information about Intel RDT CMT and MBM, please refer to:
https://github.com/opencontainers/runc/issues/2519
Signed-off-by: Paweł Szulik <pawel.szulik@intel.com>
> config-linux: Add Intel RDT CMT and MBM Linux support

- config-linux.md
cgroups v2 supports secure delegation of cgroups.  Accordingly,
control over a cgroup (that is, creation of new child cgroups and
movement of processes and threads among the cgroup subtree exposed
to a container) can be safely delegated to a container.  Adjusting
the ownership enables real-world use cases like systemd-based
containers fully isolated in user namespaces.
To encourage adoption of this feature, and secure implementation,
define the semantics of cgroup ownership.  Changing/setting the
cgroup ownership is only allowed on cgroups v2, and the specific
files whose ownership can be change are mentioned.
In terms of current practice, this is already the behaviour of crun
(which also chown's the memory.oom.group file), and there is a pull
request for runc: …
> specify cgroup ownership semantics

- config-linux.md
Not all files listed in /sys/kernel/cgroup/delegate necessarily
exist in all cgroups.  For example, see this issue and PR:
- https://github.com/opencontainers/runc/issues/3387
- https://github.com/opencontainers/runc/pull/3389
Expand the cgroup ownership semantics to ensure that runtime authors
are aware of this possibility and implementations handle it
gracefully.
> cgroup ownership: clarify that some files may not exist

- schema/README.md
Using a fixed version number is not very convenient 
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
> schema: update README.md

- config-linux.md
- specs-go/config.go
[sched: Cgroup SCHED_IDLE support](https://lore.kernel.org/lkml/162971078674.25758.15464079371945307825.tip-bot2@tip-bot2/#r) is introduced in Linux 5.15
we can mark a container SCHED_IDLE with this feature which means its sched weight are configured to the minimum
see also #1135
> config-linux: add idle option for container cgroup

- schema/Makefile
- schema/README.md
Overriding `GOPATH` may cause some problems
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
> schema: make with golang 1.16

- config-windows.md
- specs-go/config.go
Updated the documentation about Windows CPU for containers and the expectations that each of the properties have. This is taken directly from the Microsoft wording at: https://docs.microsoft.com/en-us/virtualization/api/hcs/schemareference#Container_Processor and is also referenced in the markdown for clarity.
Signed-off-by: Justin Terry <jlterry@amazon.com>
> Update Windows CPU comments

- specs-go/config.go
Previously unexported linuxBlockIODevice prevented fully defined
LinuxWeightDevice and LinuxThrottleDevice literals, making them
less user-friendly than the rest of the interface.
This solves issue #1067 (closed without a fix).
> specs-go: export LinuxBlockIODevice

- config.md
- specs-go/config.go
the config values should contain a value that means "do not modify it" within its range of values. for `int64` in other cases, we usually use `0` to express this meaning, but in `cpu.idle`, `0` can not be regarded as this meaning.
by changing the type from `int64`to `*int64`, we can use `nil` solve this problem
> config-linux: update type of LinuxCPU.Idle  to *int64

- schema/config-linux.json
commit 9d363b36f6a7db184b0f7cc67b6f79204fb50107 added the feature but
didn't update the json schema file.
> schema: add cpu idle

- specs-go/config.go
We now list the available `LinuxSeccompFlag` values as part of the runtime spec.
cc @alban
> Add available `LinuxSeccompFlag`s

- config.md
- schema/config-schema.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
add the domainname entity so that container runtimes can add special handling similar to hostname. The current workaround of adding a sysctl for kernel.domainname only works with rootful execution in most cases. This will allow for rootless execution.
container runtimes will be able to add special handling as they do for hostname, using setdomainname to add the entry to /proc/sys/kernel/domainname.
Signed-off-by: Charlie Doern <cdoern@redhat.com>
> add domainname spec entity

- config-linux.md
- schema/defs-linux.json
- specs-go/config.go
Linux 5.19 (https://github.com/torvalds/linux/commit/c2aa2dfef243) introduced a new seccomp flag: SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV
It is useful for seccomp notify when handling notification from Golang programs which are often preempted by the runtime with SIGURG.
> seccomp: Add flag SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV

- config-linux.md
- schema/config-linux.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
This setting can be used to mimic cgroup v1 behavior on cgroup v2,
when setting the new memory limit during update operation.
In cgroup v1, a limit which is lower than the current usage is rejected.
In cgroup v2, such a low limit is causing an OOM kill.
Ref: https://github.com/opencontainers/runc/issues/3509
> config-linux: add memory.checkBeforeUpdate

- config-linux.md
- schema/config-linux.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
Burstable CFS controller is introduced in Linux 5.14. This helps with
parallel workloads that might be bursty. They can get throttled even
when their average utilization is under quota. And they may be latency
sensitive at the same time so that throttling them is undesired.
This feature borrows time now against the future underrun, at the cost
of increased interference against the other system users, by introducing
`cfs_burst_us` into CFS bandwidth control to enact the cap on unused
bandwidth accumulation, which will then used additionally for burst.
The patch adds the support/control for CFS bandwidth burst.
Fixes https://github.com/opencontainers/runtime-spec/issues/1119
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
> config-linux: add CFS bandwidth burst

- ChangeLog
- specs-go/version.go
Call for vote: https://groups.google.com/a/opencontainers.org/g/dev/c/fnCiFoXBsiI/m/1jQm5OArBAAJ
Closes Tue Jan 31 10:25:29 AM UTC 2023
* config: change prestart hook spec to match reality (#1169)
* config-linux: mark memory.kernel[TCP] as NOT RECOMMENDED (#1093)
* cgroup: add cgroup v2 support (#1040)
* seccomp: allow to override errno return code (#1041)
* seccomp: Add support for SCMP_ACT_KILL_PROCESS (#1044)
* Update seccomp architectures to support RISCV64 (#1059)
* Add support for SCMP_ACT_KILL_THREAD (#1064)
* Add Seccomp Notify support using UNIX sockets and container metadata (#1074)
* config-linux: Add Intel RDT CMT and MBM Linux support (#1076)
* seccomp: allow to override default errno return code (#1087)
* Introduce zos as platform (#1095)
* config-linux: add idle option for …
> Release v1.1.0-rc.1

- config-linux.md
- config.md
- schema/config-linux.json
- schema/defs-linux.json
- schema/test/config/good/spec-example.json
- specs-go/config.go
The time namespace is a new kernel feature available in 5.6+ to
isolate the system monotonic and boot-time clocks.
I'm sorry I mistook and closed the existing request https://github.com/opencontainers/runtime-spec/pull/1062
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
> Add support for time namespace

- runtime.md
The sentence looked like as if it required a specific indentation pattern.
Fix #1177
> runtime: remove `When serialized in JSON, the format MUST adhere to the following pattern`

- config.md
The former wording was inconsistent with runc, crun, youki, etc.
Several `mount(8)` options such as `X-mount.mode` are unimplemented in those OCI runtimes, and vice versa (`tmpcopyup`, `rro`, etc.)
The option table added in this commit conforms to runc 1.1, but `acl` and `noacl` are excluded as the runc implementation seems wrong. (runc issue: https://github.com/opencontainers/runc/issues/3738)
> config: clarify Linux mount options

- config-linux.md
Clarify that device nodes need not be under `/dev`, but that the runtime need to
be informed of all the device nodes that are used by the
container.
Virtual-machine based runtimes such as Kata Containers need to be able to
perform adjustment on device nodes, and cannot be required to deep-scan
file-systems to do so.
The proposed wording was chosen to avoid any regression for any workload
mounding nodes elsewhere, while at the same time clarifying that correct
behaviour cannot be guaranteed if a device node is created on the host and used
by the container without being passed in the devices list.
This fixes issue #1147.
Signed-off-by: Christophe de Dinechin <christophe@dinechin.org>
> config-linux: Clarify where device nodes can be created

- config-linux.md
fix time_namespaces url error.
> fix config-linux.md url error

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- .tool/version-doc.go
- Makefile
- schema/validate.go
* Add Go 1.20 to GitHub actions matrix
* Updates actions/setup-go from v1 to v3. (Resolves deprecation warnings in GitHub actions around Node 12. Reference [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)) 
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> Add Go 1.20 support

- config-linux.md
- specs-go/config.go
The previous non-rsvd max/limit_in_bytes does not account for reserved
huge page memory, making it possible for a process to reserve all the
huge page memory, without being able to allocate it (due to hugetlb
cgroup page fault accounting restrictions).
In practice this makes it possible to successfully mmap more huge page
memory than allowed via the cgroup settings, but when using the memory
the process will get a SIGBUS and crash. This is bad for applications
trying to mmap at startup (and it succeeds), but the program crashes
when starting to use the memory. eg. postgres is doing this by default.
This patch updates and clarifies `LinuxResources.HugepageLimits` and
`LinuxHugepageLimit` by defaulting the configurations go to rsvd hugetlb
cgroup (when supported) and fallback to page fault …
> config-linux: add support for rsvd hugetlb cgroup

- schema/config-linux.json
commit 36bb632767af9022bd2ede974d2cadb6c318be8c introduced the issue.
> schema: fix schema for timeOffsets

- ChangeLog
- specs-go/version.go
Call for vote: https://groups.google.com/a/opencontainers.org/g/dev/c/fnCiFoXBsiI/m/fbbmbs19EQAJ
Closes Tue Apr 4 03:33:57 AM UTC 2023
- - -
After releasing v1.1.0-rc.2, I propose feature-freezing the main branch until releasing v1.1.0 GA, with an exception for PRs that were opened before proposing v1.1.0-rc.2. (e.g., #1188 #1190 #1191)
- - -
See https://github.com/opencontainers/runtime-spec/pull/1175
* config-linux: add support for rsvd hugetlb cgroup (#1116)
* features: add `features.md` to formalize the `runc features` JSON (#1130)
* config-linux: add support for time namespace (#1151)
* config-linux: clarify where device nodes can be created (#1148)
* runtime: remove `When serialized in JSON, the format MUST adhere to the following pattern` (#1178)
* Update CI to Go 1.20 (#1179)
* …
> Release v1.1.0-rc.2

- config-linux.md
This PR adds a note to the OCI Runtime Specification documentation, clarifying the differences in I/O throttling behavior between cgroup v1 and cgroup v2. Specifically, it mentions that I/O throttling settings in cgroup v1 apply only to Direct I/O due to kernel implementation constraints, while this limitation does not exist in cgroup v2.
By providing this information, users will be better informed about these differences and can make more appropriate decisions when configuring.
> Clarify I/O throttling differences between cgroup v1 and v2

- config.md
- schema/config-schema.json
- schema/defs-linux.json
- specs-go/config.go
extend the process struct to represent scheduling attributes for a process based on the sched_setattr(2) syscall.
I've been playing with crun and it is currently implemented as an annotation:
- https://github.com/containers/crun/pull/1164
- https://github.com/containers/crun/pull/1166
but I think this makes sense as part of the runtime-specs without the custom hack.
> spec: add scheduler entity

- features.md
The previous example was using an invalid value of `ociVersionMax`.
> features: update Example

- RELEASES.md
Under SemVer, the suffix "-dev" actually indicates a pre-release, meaning the way we've been using the suffix indicates that "1.0.0-dev" is *older* than "1.0.0" when we've used the suffix to indicate the opposite.
With most package managers, the "+dev" suffix correctly indicates that the version is newer (i.e. 1.0.1 > 1.0.0+dev > 1.0.0), though under SemVer "+dev" build tags must be ignored when doing version comparisons (meaning 1.0.0+dev == 1.0.0 under SemVer). However,  from a SemVer perspective the unreleased version is inarguably closer to being equal to the last release than being older than it. As a specification we also allow extensibility of various parts, meaning that if someone uses an as-yet-unreleased version it seems reasonable to me for it to be treated as the same (from a …
> releases: use +dev as in-development suffix

- ChangeLog
- specs-go/version.go
See https://github.com/opencontainers/runtime-spec/pull/1175
See https://github.com/opencontainers/runtime-spec/pull/1192
* config: add scheduler entity (#1188)
* config: Add I/O Priority Configuration for process group in Linux Containers (#1191)
* config-linux: clarify I/O throttling differences between cgroup v1 and v2 (#1194)
* config-linux: chore: Update `ociVersion` in example (#1199)
* releases: use +dev as in-development suffix (#1198)
* MAINTAINERS: add Toru Komatsu (utam0k) (#1201)
* glossary: `s/features document/Features structure/g` (#1203)
* features: update Example (#1204)
* schema: fix definition for ioPriority (#1206)
* CODEOWNER: Add Toru Komatsu(@utam0k) to sync with MAINTAINERS (#1207)
- - -
[[runtime-spec VOTE] tag ae35e39 as v1.1.0-rc3 (closes Mon May 29 02:08:08 PM …
> Release v1.1.0-rc.3

- ChangeLog
- specs-go/version.go
* README.md: update chat information (#1210)
* Remove outdated meeting.ics (#1211)
* features: add a note to avoid confusion about annotations (#1212)
* config: add scheduler entity (#1188)
* config: Add I/O Priority Configuration for process group in Linux Containers (#1191)
* config-linux: clarify I/O throttling differences between cgroup v1 and v2 (#1194)
* config-linux: chore: Update `ociVersion` in example (#1199)
* releases: use +dev as in-development suffix (#1198)
* MAINTAINERS: add Toru Komatsu (utam0k) (#1201)
* glossary: `s/features document/Features structure/g` (#1203)
* features: update Example (#1204)
* schema: fix definition for ioPriority (#1206)
* CODEOWNER: Add Toru Komatsu(@utam0k) to sync with MAINTAINERS (#1207)
* config-linux: add support for rsvd hugetlb cgroup …
> Release v1.1.0

- config.md
Adding new fields for MOUNT_ATTR_IDMAP had the flaw that users
specifying these fields with older runtimes would result in the fields
being ignored and incorrect mounts being configured. In addition, there
is no text in the specification indicating whether MOUNT_ATTR_IDMAP
should be applied with AT_RECURSIVE (which matters for rbind idmapped
mounts).
In retrospect, the addition of the fields should've included new (dummy)
mount options that would cause errors on older runtimes. Unfortunately,
we have had a runtime-spec release since then so we cannot MUST these
new mount options, but we can SHOULD them.
Fixes #1216
Resolves the main issue motivating the urgency of #1219 (though that feature is still something we should have).
Fixes: …
> config: add idmap and ridmap mount options

- config.md
We tried to make runc enforce abs dest path several times, and always had to revert it due to breakin users. The last occurrence is this one, in which we detected a few places not up to date and decided to revert the "throw an error" behavior:
https://github.com/opencontainers/runc/issues/3944#issuecomment-1669261383
I don't see any reason to force abs dst paths on Linux, as far as I know there is no security bug nor anything. Let's just relax the spec wording, matching all the runtimes behavior when the paths is relative, and be done with it.
---
cc @thaJeztah
> mount: Allow relative mount destinations on Linux

- config.md
Current documentation talks about bind/rbind and various propagation flags (shared, slave, private, unbindable etc.) as being filesystem-specific options, and refers to mount(8) section describing filesystem-specific options.
That is wrong, because bind mounts are a separate class of mounts, not related to file systems.
Fix the confusion, and link to sharedsubtree.txt kernel document as it happens to be the best source of information about the topic (not counting the kernel sources).
> config: improve bind mount and propagation doc

- specs-go/config.go
- relates to / update https://github.com/opencontainers/runtime-spec/pull/1008
Hooks.Prestart was deprecated in c1662686cff159595277b79322d0272f5182941b (v1.0.2), but the field did not have a correctly formatted deprecation comment.
This patch updates the field's GoDoc to have a correctly formatted deprecation comment, which will allow linters and IDEs to detect the deprecation status of this feature.
> specs-go: add missing deprecation comment for Hooks.Prestart

- specs-go/config.go
- updates https://github.com/opencontainers/runtime-spec/pull/1093
Support for kernel-memory limits was deprecated in the kernel, and documented as "NOT RECOMMENDED" (or "SHOULD NOT" use) in  v1.1.0-rc.1 through commit f02cd4a4273f5cf4898df4feee7dcf0d08756029.
This patch marks the field as deprecated in the go implementation of the spec, so that linters and editors produces a warning and consumers get notified of its status.
> specs-go: mark LinuxMemory.Kernel as deprecated

- features.md
- schema/features-schema.json
- specs-go/features/features.go
Fix #1202 , for prohibiting propagation of insecure annotations from remote images into OCI runtime `config.json`
https://github.com/opencontainers/image-spec/pull/1061/files#r1194531089
> features: add potentiallyUnsafeConfigAnnotations

- config.md
These annotations are specified as part of the official conversion process from an OCI image configuration to an OCI runtime configuration since v1.0.0-rc7 of the image-spec but they were never officially specified in
The fact these are not allowed by the current runtime-spec causes some issues with inter-spec compatibility. In order for tools like umoci to be able to do this generation properly, we need to allow this namespace to be used.
Ref: https://github.com/opencontainers/image-spec/blob/v1.1.0-rc2/conversion.md
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
> config: add support for org.opencontainers.image annotations

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
N/A
This change updates actions/checkout to v4, actions/setup-go to v5, and golangci/golangci-lint-action to v4 to resolve NodeJS 16 deprecation warnings in CI.
CI checks pass without deprecation warnings
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update GitHub Actions packages to resolve warnings in CI

- ChangeLog
- specs-go/version.go
It's time we release the new patch version since we have met the milestone for ~~v1.1.1~~ `v1.2.0`
https://github.com/opencontainers/runtime-spec/milestone/19
Previous release: https://github.com/opencontainers/runtime-spec/pull/1213
Additions:
* config: add idmap and ridmap mount options (#1222)
* config.md: allow empty mappings for [r]idmap (#1224)
* features-linux: Expose idmap information (#1219)
* mount: Allow relative mount destinations on Linux (#1225)
* features: add potentiallyUnsafeConfigAnnotations (#1205)
* config: add support for org.opencontainers.image annotations #1197
Minor fixes:
* config: improve bind mount and propagation doc (#1228)
Documentation, CI & Governance:
* fix link to hooks in features (#1226)
* specs-go: add missing deprecation comment for Hooks.Prestart …
> Release v1.2.0

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
N/A
This change adds Go v1.21 and v1.22 to GitHub actions CI matrix and drops Go v1.19 and v1.20 which will no longer receives updates. Additionally it updates golangci-lint version to v1.56.1 which has Go v1.22 support.
- https://go.dev/doc/go1.21
- https://go.dev/doc/go1.22
> Add Go v1.21 and v1.22 to GitHub Actions CI matrix

- CODEOWNERS
- EMERITUS.md
- MAINTAINERS
Happy to still be brought into conversations, but do not want to slow progress of the active maintainers.
🐐🧁🧡
Also, building out the EMERITUS from the past folks that have already retired out of being maintainers.
> MAINTAINERS: move vbatts to EMERITUS

- config-linux.md
- config.md
- schema/config-schema.json
- specs-go/config.go
This allows to set initial and final CPU affinity for a process being run in a container, which is needed to solve the issue described in https://github.com/opencontainers/runc/issues/3922.
This is an alternative to #1252.
> Add CPU affinity to executed processes

- config.md
Description of `execCPUAffinity.final` field (added in #1253) said that if it's not set or empty, the final affinity is the one of container's cgroup. This was done because we thought the kernel changes process' CPU affinity to one of cgroup. It's not the case ([see here](https://github.com/opencontainers/runtime-spec/pull/1253/commits/119ae426a12298a57b5d0828017c878f34fb7cf0#r1635517428)).
To keep runtimes simple, it makes sense to not do anything if the final affinity is not explicitly set. This change does just that.
> config: simplify final CPU affinity rule

- config.md
This PR addresses an expired link for "Naming a Volume" in the config.md file. The original link was no longer accessible, and based on the context, I have identified a new link that likely aligns with the documentation's intended reference.
> doc: fix expired link for "Naming a Volume" in config.md

- config-linux.md
- schema/defs-linux.json
- specs-go/config.go
The following constants are defined in the main branch of libseccomp, but not included in its latest release (v2.5) yet:
* `SCMP_ARCH_LOONGARCH64`  (seccomp/libseccomp@6966ec7)
* `SCMP_ARCH_M68K`         (seccomp/libseccomp@dd5c9c2)
* `SCMP_ARCH_SH`              (seccomp/libseccomp@c12945d)
* `SCMP_ARCH_SHEB`         (seccomp/libseccomp@c12945d)
These constant names are unlikely to change before v2.6 GA, so we can safely refer to them in specs-go.
Replaces:
- https://github.com/opencontainers/runtime-spec/pull/1187
> specs-go: sync SCMP_ARCH_* constants with libseccomp main

- .github/workflows/lint.yml
- schema/config-schema.json
In order to prevent like https://github.com/opencontainers/runtime-spec/pull/1255
It works fine: https://github.com/utam0k/runtime-spec/actions/runs/9534058439/job/26278029545
> ci: Add a github actions workflow for lint

- config-windows.md
- schema/config-windows.json
- specs-go/config.go
This PR adds support for certain CRI fields in OCI runtime spec for supporting CPU affinity for windows containers.
CRI PR : https://github.com/kubernetes/kubernetes/pull/124285 
Github issue: https://github.com/kubernetes/kubernetes/issues/125262
KEP: https://github.com/kubernetes/kubernetes/issues/125262
> Add support for windows CPU affinity

- config.md
Correct `prestart` hook description in summary
It looks like the previous description was copied from the wrong line.   Update the `prestart (Deprecated)` hook's timing from being called "after the start operation is invoked but before the user-specified command executes"  to "during the create operation, after the runtime environment is created and before pivot root or any equivalent operation."
> Correct `prestart` hook description in summary

- config-linux.md
- specs-go/config.go
libseccomp v2.6.0 was released on Jan 23, 2025.
https://github.com/seccomp/libseccomp/releases/tag/v2.6.0
> config-linux: update for libseccomp v2.6.0

- config-zos.md
- config.md
- schema/config-zos.json
- schema/defs-zos.json
- schema/test/config/good/zos-example.json
- specs-go/config.go
This PR proposes updates to the OCI runtime spec with z/OS platform-specific details, including adding **namespaces**, adding **noNewPrivileges** flag, and removing **devices**.  These changes are currently in use by the IBM z/OS Container Platform (zOSCP) product - details can be found here: [https://www.ibm.com/products/zos-container-platform](https://www.ibm.com/products/zos-container-platform).
**Note:** The "removing of devices" is not considered to be an incompatible change since no user would have been using the z/OS-specific portion of the runtime spec, prior to the initial zOSCP release.
> zos updates

- config-linux.md
There is a subtle difference in syntax between Seccomp's defaultErrnoRet and errnoRet, so i will unify the syntax.
https://github.com/opencontainers/runtime-spec/blob/a5b01166ad3fdf111b1e427abe35ce2538f85f50/config-linux.md?plain=1#L722
https://github.com/opencontainers/runtime-spec/blob/a5b01166ad3fdf111b1e427abe35ce2538f85f50/config-linux.md?plain=1#L797
Or you could just reference one of them like this...
https://github.com/opencontainers/runtime-spec/blob/a5b01166ad3fdf111b1e427abe35ce2538f85f50/config-linux.md?plain=1#L718
> Fix description of errnoRet in Seccomp

- ChangeLog
- specs-go/version.go
**Changes with v1.2.1:**
Previous release: https://github.com/opencontainers/runtime-spec/pull/1242
Additions:
* zos updates (#1273)
* Add support for windows CPU affinity (#1258)
* specs-go: sync SCMP_ARCH_* constants with libseccomp main (#1229)
* Add CPU affinity to executed processes (#1253)
* config-linux: describe the format of cpus and mems (#1253)
Minor fixes:
Documentation, CI & Governance:
* Fix description of errnoRet in Seccomp (#1277)
* config-linux: update for libseccomp v2.6.0 (#1276)
* Correct `prestart` hook description in summary (#1275)
* ci: Add a github actions workflow for lint (#1257)
* update http links to https (#1269)
* doc: fix the invalid hyperlink naming-a-volume (#1268)
* ci: remove redundunt actions (#1256)
* chore: format JSON file `make -C schema fmt` …
> Release v1.2.1

- implementations.md
It's a bit awkward really, since that nspawn isn't the WHOLE repo on GitHub unlike the others...
> add systemd-nspawn to implementations.md

- config-linux.md
- features-linux.md
- schema/config-linux.json
- schema/defs-linux.json
- schema/features-linux.json
- schema/test/config/bad/linux-netdevice.json
- schema/test/config/good/linux-netdevice.json
- schema/test/features/good/runc.json
- specs-go/config.go
- specs-go/features/features.go
The proposed "netdevices" field provides a declarative way to specify which host network devices should be moved into a container's network namespace.
This approach is similar than the existing "devices" field used for block devices but uses a dictionary keyed by the interface name instead.
The proposed scheme is based on the existing representation of network device by the `struct net_device`
https://docs.kernel.org/networking/netdevices.html.
This proposal focuses solely on moving existing network devices into the container namespace. It does not cover the complexities of network configuration or network interface creation, emphasizing the separation of device management and network configuration.
A list of real use cases that justify this proposal is:
1.  **Pre-Configuring Physical …
> Define Linux Network Devices

- config-linux.md
- features-linux.md
- features.md
- schema/config-linux.json
- specs-go/config.go
Add a new "schemata" field to the Linux IntelRdt configuration. This addresses the complexity of separate schema fields and resolves the issue of supporting currently uncovered RDT features like L2 cache allocation and CDP (Code and Data Prioritization).
The new field is for specifying the complete schemata (all schemas) to be written to the schemata file in Linux resctrl fs. The aim is for simple usage and runtime implementation (by not requiring any parsing/filtering of data or otherwise re-implement parsing or validation of the Linux resctrl interface) and also to support all RDT features now and in the future (i.e. schemas like L2, L2CODE, L2DATA, L3CODE and L3DATA and who knows L4 or something else in the future).
Behavior of existing fields is not changed but it is required that the …
> config-linux: add schemata field to IntelRdt

- principles.md
Hello,
This is my first PR to the repo. I am proposing to use the commonly used spelling of DevOps:
```
s/devOps/DevOps/
```
Your feedback is much appreciated,
> principles: fix typo

- config-linux.md
- schema/config-linux.json
- specs-go/config.go
Add a parameter for enabling per-container resctrl monitoring.
This supersedes the previous `enableCMT` and `enableMBM` settings whose functionality was very vaguely specified. Separate parameter for every monitoring metric does not seem to make much sense, in particular because in the resctrl filesystem it is not possible to selectively enable a subset of the monitoring features. You always get all the metrics that the system provides. Also, with separate settings (and corresponding check if the specific metric is available) the user cannot specify "enable whatever is available" - setting everything to "true" might fail because one of the metrics is not available on the platform. In addition, having separate parameters is very future-unproof, making support for new monitoring metrics …
> config-linux: add intelRdt.enableMonitoring

- config-linux.md
- features-linux.md
- features.md
- schema/config-linux.json
- schema/defs-linux.json
- specs-go/config.go
- specs-go/features/features.go
Enable setting a NUMA memory policy for the container. New linux.mempolicy object contains inputs to the set_mempolicy(2) syscall.
> Add support for Linux memory policy

- specs-go/features/features.go
Accidentally left out from d2f4f9097a834934fd8232cfc54ddc3679a44764 which added the "linux.intelRdt.schemata" field to the config.
> specs-go/features: add linux.intelRdt.schemata field

- config-linux.md
Specify "/" as an explicit value for linux.intelRdt.closID to assign a container to the default CLOS, corresponding to the root of the resctrl filesystem.
This addition is important after the recently introduced intelRdt.enableMonitoring field. There is no way to express "enable monitoring but keep the container in the default CLOS". Users would otherwise have to rely on pre-created CLOSes or may quickly exhaust available CLOS entries - in some configurations the number of available CLOSes (on top of the default) may be as low as three.
> [!NOTE]
> Alternative names I considered were e.g. `.`, `/default`, `/root`, `default/`, `root/` (i.e. something that is not a possible/valid > name in the resctrl fs).
> config-linux: define default clos for linux.intelRdt

- config-linux.md
- specs-go/config.go
The history of this is a little complicated, but in short there is an
argument to be made that several misunderstandings resulted in the spec
sometimes implying (and runtimes interpreting) a pids.limit value of 0
to be equivalent to "max" or otherwise having unfortunate handling of
the value.
The slightly longer background is the following:
1. When commit 834fb5db52bc ("spec: linux: add support for the PIDs
cgroup") added support, we did not yet have textual documentation of
cgroup configuration values. In addition, we had not yet started
using pointers to indicate optional fields and detect unset fields.
However, the initial commit did imply that pids.limit=0 should be
treated as a real value.
2. Commit 2ce2c866ffe1 ("runtime: config: linux: add cgroups
information") labeled "pids.limit" …
> linux: clarify pids cgroup settings
